#!/usr/bin/env bash
# ============================================================================
# mediastack.sh — install, configure, run, update, back up and diagnose the
# mediastack. Run without arguments for an explained command list.
#
# Design rules this script follows:
#   * .env is the single source of truth; tracked files are NEVER written at
#     runtime. Generated state goes to gitignored places (local/, backups/).
#   * Fail loud: no silent fallbacks. Every failure states what and how to fix.
#   * Service discovery is label-driven (mediastack.* labels in compose.d/*):
#     this script contains no hardcoded service lists.
# ============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

ENV_FILE="$SCRIPT_DIR/.env"
# Where everything lives (README: "Where things live"). The repo root holds
# the code and .env; what you write goes in custom/, what the script
# generates in local/ (delete local/ and the script rebuilds it).
CUSTOM_DIR="$SCRIPT_DIR/custom"
OVERRIDE_FILE="$CUSTOM_DIR/override.yml"          # your patches to shipped services
DROPIN_DIR="$CUSTOM_DIR/compose.d"                # your own services, one file each
PROXY_DIR="$CUSTOM_DIR/proxy.d"                   # your own Traefik routes
TRASH_OVERRIDES="$CUSTOM_DIR/trash-overrides.yml" # your TRaSH score overrides
LOCAL_DIR="$SCRIPT_DIR/local"
OVERLAY_FILE="$LOCAL_DIR/vpn-overlay.yml"         # VPN membership, generated by vpn_gen
PINS_FILE="$LOCAL_DIR/pins.yml"                   # pinned images (rollback)
WIRED_FILE="$LOCAL_DIR/wired"                     # marker: wire has completed once
STATE_DIR="$LOCAL_DIR/state"                      # pending work: one file per marker (state_get/state_set)
ENV_BACKUP_DIR="$LOCAL_DIR/env-backups"           # .env before each schema migration
ENV_BACKUP_KEEP=10                                # the oldest (your original) + the newest 9
SCRIPT_SCHEMA=29

# Libraries — sourced, never executed (mode 644); every source line lives
# here so the load order is visible in one place. Each lib says at its top
# what it holds; the entrypoint keeps only what running the stack needs:
# the compose/service and container-inspect helpers, the health verdict,
# provisioning, up/down/enable/disable/logs, status, the verb registry and
# main(). Every other verb lives in a lib named for it. Libs call entrypoint
# helpers at call time only.
# shellcheck source=lib/common.sh
source "$SCRIPT_DIR/lib/common.sh"
# shellcheck source=lib/frontdoor.sh
source "$SCRIPT_DIR/lib/frontdoor.sh"
# shellcheck source=lib/integrations.sh
source "$SCRIPT_DIR/lib/integrations.sh"
# shellcheck source=lib/migrations.sh
source "$SCRIPT_DIR/lib/migrations.sh"
# shellcheck source=lib/env.sh
source "$SCRIPT_DIR/lib/env.sh"
# shellcheck source=lib/vpn.sh
source "$SCRIPT_DIR/lib/vpn.sh"
# shellcheck source=lib/edge.sh
source "$SCRIPT_DIR/lib/edge.sh"
# shellcheck source=lib/backup.sh
source "$SCRIPT_DIR/lib/backup.sh"
# shellcheck source=lib/manifest.sh
source "$SCRIPT_DIR/lib/manifest.sh"
# shellcheck source=lib/doctor.sh
source "$SCRIPT_DIR/lib/doctor.sh"
# shellcheck source=lib/audit.sh
source "$SCRIPT_DIR/lib/audit.sh"
# shellcheck source=lib/recycle.sh
source "$SCRIPT_DIR/lib/recycle.sh"
# shellcheck source=lib/footprint.sh
source "$SCRIPT_DIR/lib/footprint.sh"
# shellcheck source=lib/notify.sh
source "$SCRIPT_DIR/lib/notify.sh"
# shellcheck source=lib/authentik.sh
source "$SCRIPT_DIR/lib/authentik.sh"
# shellcheck source=lib/configure.sh
source "$SCRIPT_DIR/lib/configure.sh"
# shellcheck source=lib/lifecycle.sh
source "$SCRIPT_DIR/lib/lifecycle.sh"
# shellcheck source=lib/access.sh
source "$SCRIPT_DIR/lib/access.sh"
# shellcheck source=lib/newservice.sh
source "$SCRIPT_DIR/lib/newservice.sh"
# shellcheck source=lib/trash.sh
source "$SCRIPT_DIR/lib/trash.sh"

load_env() {
    # NOTE: .env is deliberately NOT sourced — compose reads it natively, and
    # bash `source` would execute space-containing values ("Tue 04:00") as
    # commands. All script reads go through env_get.
    [[ -f "$ENV_FILE" ]] || die ".env not found. Run: ./mediastack.sh configure"
    migrate_env
    env_validate
}

# --------------------------------------------------------- compose layer --
user_compose_files() { # -f args for what you wrote: each drop-in service (sorted), then the override
    # (last, so it can patch a drop-in too). Checked here, in the caller's
    # shell — a die inside $( ) would only end the subshell.
    [[ -e "$SCRIPT_DIR/docker-compose.override.yml" ]] && die "docker-compose.override.yml is at the repo root, where mediastack no longer reads it.
  Your patches to shipped services belong in custom/override.yml, a service of
  your own in custom/compose.d/<name>.yml (docs/adding-a-service.md). Move it,
  then retry — nothing was started."
    dropins_check
    USER_FILES=()
    local f
    for f in "$DROPIN_DIR"/*.yml; do [[ -e "$f" ]] && USER_FILES+=(-f "$f"); done
    [[ -e "$OVERRIDE_FILE" ]] && USER_FILES+=(-f "$OVERRIDE_FILE")
    return 0
}

yaml_services() { # yaml_services FILE -> the service names under its top-level services: (block YAML)
    awk '/^services:[[:space:]]*(#.*)?$/ { ins = 1; ind = 0; next }
         ins && /^[^[:space:]#]/ { ins = 0 }
         ins && /^[[:space:]]+[A-Za-z0-9_.-]+:[[:space:]]*(#.*)?$/ {
             match($0, /^[[:space:]]+/)
             if (!ind) ind = RLENGTH
             if (RLENGTH == ind) { k = $0; sub(/^[[:space:]]+/, "", k); sub(/:.*/, "", k); print k }
         }' "$1"
}

dropins_check() { # a drop-in adds services — it never redefines a shipped one or another drop-in's
    local f s owner
    local -A seen=()
    for f in compose.d/*.yml; do
        for s in $(yaml_services "$f"); do seen[$s]="shipped ($f)"; done
    done
    for f in "$DROPIN_DIR"/*.yml; do
        [[ -e "$f" ]] || continue
        [[ -n "$(yaml_services "$f")" ]] || die "$f defines no services (expected a top-level 'services:' block).
  Fix or remove it, then retry."
        for s in $(yaml_services "$f"); do
            owner=${seen[$s]:-}
            [[ -z "$owner" ]] || die "$f defines '$s', which is already defined — $owner.
  A drop-in adds a service of your own; to change a shipped one, patch it in
  custom/override.yml instead. Rename or move it, then retry."
            seen[$s]="another drop-in ($f)"
        done
    done
    return 0
}

DC() { # compose wrapper: project dir pinned, your files, the VPN overlay and pins applied
    # every file is passed with -f (which also disables compose's automatic
    # override merge): base, your drop-ins and override, the generated VPN
    # membership overlay (authoritative over your files), pins last (pins win)
    user_compose_files
    local files=(-f docker-compose.yml "${USER_FILES[@]}")
    [[ -e "$OVERLAY_FILE" ]] && files+=(-f "$OVERLAY_FILE")
    [[ -s "$PINS_FILE" ]] && files+=(-f "$PINS_FILE")
    [[ " $* " == *" config "* ]] || INSPECT_JSON=""   # see CACHE RULE at c_inspect
    sudo docker compose --project-directory "$SCRIPT_DIR" "${files[@]}" "$@"
}

compose_renders() { DC config >/dev/null; } # rc-only; compose errors pass through

RENDERED_JSON=""
USER_FILES=()      # user_compose_files fills it: -f args for custom/
INSPECT_JSON=""   # `docker inspect` cache — see CACHE RULE at c_inspect
render() { # cache rendered config as json for discovery
    # CACHING SEMANTICS: helpers run inside $( ) subshells, so a render
    # triggered there does NOT populate the parent shell. Any function that
    # reads $RENDERED_JSON directly, or loops service helpers, must call
    # `render` in its own (parent) scope first — both for correctness and to
    # avoid one `docker compose config` per helper call.
    [[ -n "$RENDERED_JSON" ]] && return 0
    user_compose_files   # here, not inside DC's $( ): a misplaced file must stop the caller
    # --profile "*": discovery sees the whole catalogue, not just enabled
    # services — otherwise disabled services vanish from backups and audits.
    local rerr
    rerr=$(mktemp)
    if ! RENDERED_JSON=$(DC --profile "*" config --format json 2>"$rerr"); then
        echo "${C_RED}compose said:${C_RST}" >&2
        sed 's/^/  /' "$rerr" >&2; rm -f "$rerr"
        die "docker compose could not render the config (see compose's message above).
  Needs compose >= 2.24 ('include:' + wildcard profiles); check .env syntax.
  Just removed one of your services (custom/)? Its generated stanza is
  stale: ./mediastack.sh up regenerates local/vpn-overlay.yml."
    fi
    rm -f "$rerr"
}

svc_all()      { render; jq -r '.services | keys[]' <<<"$RENDERED_JSON"; }
svc_label()    { render; jq -r --arg s "$1" --arg l "$2" '.services[$s].labels[$l] // ""' <<<"$RENDERED_JSON"; }
svc_managed()  { svc_managed_where mediastack.managed true; }
svc_managed_where() { # svc_managed_where LABEL VALUE — managed services whose LABEL == VALUE, one jq
    render
    jq -r --arg l "$1" --arg v "$2" '
        [ .services | to_entries[]
          | select(.value.labels["mediastack.managed"] == "true" and .value.labels[$l] == $v)
          | .key ] | sort[]' <<<"$RENDERED_JSON"
}
svc_enabled_managed()  { _svc_managed_by_profile true; }
svc_disabled_managed() { _svc_managed_by_profile false; }
# is_user_facing <svc> — true when the service is household-facing (updates
# notify the 'users' stream). A ${STEM}_USER_FACING override in .env (set via
# set-user-facing) wins over the fragment's mediastack.user_facing default.
is_user_facing() {
    local ov; ov=$(env_get "$(uvar "$1")_USER_FACING" "")
    [[ -n "$ov" ]] && { [[ "$ov" == true ]]; return; }
    [[ "$(svc_label "$1" mediastack.user_facing)" == true ]]
}
_svc_managed_by_profile() { # one env read + one jq, same test as svc_enabled per service
    render
    local profiles; profiles=",$(env_get COMPOSE_PROFILES),"
    jq -r --arg p "$profiles" --argjson want "$1" '
        [ .services | to_entries[]
          | select(.value.labels["mediastack.managed"] == "true")
          | .key as $k | select(($p | contains("," + $k + ",")) == $want) | $k ] | sort[]' <<<"$RENDERED_JSON"
}
svc_exists()   { svc_all | grep -qx "$1"; }

# Shards (docs/roadmap.md: Architecture rules — Shards). A service's private
# containers (its database, its worker) are MEMBERS of its shard: each carries
# `mediastack.shard: <primary>` and no mediastack.managed, shares the primary's
# profile, runs as the primary's UID and keeps its data inside the primary's
# folders — so provisioning, ownership, fix-perms and backups (all keyed to the
# primary's folders) cover members unchanged. Only verbs that act on containers
# expand a primary to its shard: update, restore, logs, disable, status, doctor.
svc_members() { # svc_members <primary> -> its member services, sorted
    render
    jq -r --arg p "$1" '.services | to_entries[] | select(.value.labels["mediastack.shard"] == $p) | .key' \
        <<<"$RENDERED_JSON" | sort
}
svc_shard() { # svc_shard <primary>... -> each primary followed by its members
    local s
    for s in "$@"; do echo "$s"; svc_members "$s"; done
}
shard_health() { # shard_health <primary> -> the primary's health, or "degraded" when a member is not up
    local m st h
    for m in $(svc_members "$1"); do
        st=$(c_state "$(svc_cname "$m")"); h=$(c_health "$(svc_cname "$m")")
        [[ "$st" == running && "$h" != unhealthy ]] || { echo degraded; return 0; }
    done
    c_health "$(svc_cname "$1")"
}
svc_conflicts() { # svc_conflicts <svc> -> the services it may never run beside (mediastack.conflicts, either side declares)
    render
    jq -r --arg s "$1" '.services as $all
        | ([($all[$s].labels["mediastack.conflicts"] // "") | split(" ")[] | select(. != "")]
           + [$all | to_entries[] | select((.value.labels["mediastack.conflicts"] // "") | split(" ") | index($s)) | .key])
        | unique[]' <<<"$RENDERED_JSON"
}
conflicts_in() { # conflicts_in SERVICE... -> "a b" for every pair in the set that may not run together
    local s c set=" $* "
    for s in "$@"; do
        for c in $(svc_conflicts "$s"); do
            [[ "$set" == *" $c "* && "$s" < "$c" ]] && echo "$s $c"
        done
    done
    return 0
}

shard_problems() { # every shard rule the rendered config breaks, one line each (CI: test-render)
    render
    jq -r '.services as $all | $all | to_entries[] | select(.value.labels["mediastack.shard"] != null)
        | .key as $m | .value as $v | ($v.labels["mediastack.shard"]) as $p
        | if ($all[$p] == null) then "\($m): its primary \($p) does not exist"
          elif ($all[$p].labels["mediastack.managed"] != "true") then "\($m): its primary \($p) is not a managed service"
          elif ($v.labels["mediastack.managed"] != null) then "\($m): a member must not carry mediastack.managed"
          elif (($v.profiles // []) != ($all[$p].profiles // [])) then "\($m): profiles differ from its primary \($p) (members start and stop with it)"
          elif (($v.user // "") != ($all[$p].user // "")) then "\($m): runs as \($v.user // "the image default"), not as its primary \($p) (\($all[$p].user // "the image default"))"
          elif ((($all[$p].depends_on // {}) | has($m)) | not) then "\($m): its primary \($p) must depend_on it (starting the primary starts the shard)"
          else empty end' <<<"$RENDERED_JSON"
}
svc_image()    { render; jq -r --arg s "$1" '.services[$s].image' <<<"$RENDERED_JSON"; }
svc_cname()    { render; jq -r --arg s "$1" '.services[$s].container_name // $s' <<<"$RENDERED_JSON"; }
svc_port() { # host port a service is published on for its mediastack.port
    # (the CONTAINER port). Read from the rendered config, so it honours every
    # `${<SVC>_PORT:-…}` override — on the service itself, or on gluetun when
    # the service shares gluetun's namespace. Empty when nothing publishes it
    # (Traefik-only services); use svc_hostport where a host port is required.
    render
    local cport; cport=$(svc_label "$1" mediastack.port)
    [[ -n "$cport" ]] || return 0
    jq -r --arg s "$1" --argjson t "$cport" '
        ((.services[$s].network_mode // "")
         | if startswith("service:") then ltrimstr("service:") else $s end) as $pub
        | [ .services[$pub].ports[]? | select(.target == $t and .protocol == "tcp") | .published ]
        | first // ""' <<<"$RENDERED_JSON"
}
svc_hostport() { # svc_port, but a missing host port is an error (API callers)
    local p; p=$(svc_port "$1")
    [[ -n "$p" ]] || die "$1 publishes no host port for its mediastack.port label — unreachable from this host"
    echo "$p"
}
uvar()         { echo "${1^^}" | tr '-' '_' | tr -cd 'A-Z0-9_'; } # service -> env var stem (radarr-4k -> RADARR_4K)
svc_enabled()  { [[ ",$(env_get COMPOSE_PROFILES)," == *",$1,"* ]]; }
svc_url() { # where a browser reaches the service, best effort
    local s="$1" sub port domain
    [[ "$s" == traefik ]] && { echo "-"; return; }   # it IS the https edge
    domain=$(env_get TRAEFIK_DOMAIN)
    sub=$(env_get "$(uvar "$s")_HOST"); [[ -n "$sub" ]] || sub=$(svc_label "$s" mediastack.subdomain)
    # a subdomain only yields an https URL when a domain is actually configured;
    # without one, fall through to the host:port (or internal) form below rather
    # than printing a dead https://<sub>.unset
    if [[ -n "$sub" && -n "$domain" ]]; then echo "https://${sub}.${domain}"; return; fi
    port=$(svc_port "$s")
    [[ -z "$port" ]] && { echo "-"; return; }
    [[ "$(svc_label "$s" mediastack.internal)" == "true" ]] \
        && echo "internal :${port}" \
        || echo "http://$(hostname):${port}"
}
svc_deps()     { # direct dependencies: depends_on + shared network namespace
    render
    # a shard member is never a dependency of its own: it comes with its
    # primary's profile, so it is not a service to enable
    jq -r --arg s "$1" '.services as $all | $all[$s]
        | (((.depends_on // {}) | keys[]?) | select(($all[.].labels["mediastack.shard"] // "") == "")),
          (if ((.network_mode // "") | startswith("service:"))
           then (.network_mode | ltrimstr("service:")) else empty end)' \
        <<<"$RENDERED_JSON" | sort -u
}
resolve_deps() { # expand a service set to include all transitive dependencies
    local set=" $* " grew=1 s d
    while (( grew )); do
        grew=0
        for s in $set; do
            for d in $(svc_deps "$s"); do
                [[ "$set" == *" $d "* ]] || { set+="$d "; grew=1; info "  + $d (required by $s)"; }
            done
        done
    done
    echo "$set" | xargs -n1 | awk 'NF' | sort -u
}

# ---------------------------------------------------------------- mounts --
require_mounts() {
    local root path expect actual
    for root in "${ROOTS[@]}"; do
        path=$(env_get "$root"); expect=$(env_get "${root}_SOURCE")
        # a relative root means .env was copied by hand: compose resolves it
        # against compose.d/ (the include files' directory), not this folder
        [[ -z "$path" || "$path" == /* ]] \
            || die "$root is a relative path ('$path') — compose would resolve it against compose.d/, not this folder.
  Run: ./mediastack.sh configure   (it stores absolute paths; Enter keeps every other answer)"
        [[ -z "$path" || -z "$expect" ]] && continue
        actual=$(timeout 5 findmnt -rn -o SOURCE --target "$path" 2>/dev/null) || {
            die "$root ($path): mount check timed out — stale or hung network mount.
  Fix the share (e.g. 'sudo umount -l $path' then remount) and retry."
        }
        [[ "$actual" == "$expect" ]] || die "$root ($path) expected on '$expect' but found '$actual'.
  The share is not mounted — starting now would write to the wrong disk.
  Fix: 'sudo mount $path' (or check the NAS), then retry."
    done
}

# ----------------------------------------------------------- help / menu --
cmd_help() { # rendered from VERBS: one line per verb, grouped; depth lives in README
    echo "${C_BLD}Mediastack${C_RST} — usage: ./mediastack.sh <command> [args]"
    local g e usage desc w=0
    for e in "${VERBS[@]}"; do usage=$(cut -d'~' -f2 <<<"$e"); (( ${#usage} > w )) && w=${#usage}; done
    for g in Setup Run Maintain Connect Check Other Internal; do
        echo
        [[ "$g" == Internal ]] && echo "Internal (used by the panel, timers and units — not meant for hand use)" || echo "$g"
        for e in "${VERBS[@]}"; do
            [[ "$(cut -d'~' -f4 <<<"$e")" == "$g" ]] || continue
            usage=$(cut -d'~' -f2 <<<"$e"); desc=$(cut -d'~' -f5 <<<"$e")
            printf '  %-*s  %s\n' "$w" "$usage" "$desc"
        done
    done
    echo
    echo "Every verb rejects arguments it does not accept. Details, options and"
    echo "worked examples: README.md and docs/."
}

cmd_menu() {
    local opts=(up down status doctor update backup leak-test configure help exit)
    while true; do
        echo; hr "Mediastack menu"
        local i=1; for o in "${opts[@]}"; do echo "  $i) $o"; ((i++)); done
        local pick; read -r -p "Choice: " pick
        [[ "$pick" =~ ^[0-9]+$ ]] && (( pick>=1 && pick<=${#opts[@]} )) || { warn "Pick 1-${#opts[@]}"; continue; }
        local cmd="${opts[$((pick-1))]}"
        [[ "$cmd" == exit ]] && return 0
        "cmd_${cmd//-/_}" || warn "'$cmd' exited with an error (see above)"
    done
}


# ---------------------------------------------------------- provisioning --
# uid_handover — one-time ownership handover for services that switched from
# running as root to their own UID (listed in UID_HANDOVER by a migration).
# Runs only from `up`/`enable`, immediately before compose recreates them:
# stop the root-running container (it keeps creating root files, e.g. SQLite
# -wal/-shm), give its config/cache folders to its UID, then clear the list.
uid_handover() {
    local pending s uid cn croot cache media gid
    pending=$(state_get UID_HANDOVER); [[ -n "$pending" ]] || return 0
    gid=$(env_get MEDIA_GROUP_GID 13000); croot=$(env_get CONFIG_ROOT)
    cache=$(env_get CACHE_ROOT); media="$(env_get DATA_ROOT)/media"
    hr "Ownership handover: $pending"
    for s in $pending; do
        uid=$(env_get "$(uvar "$s")_UID"); [[ -n "$uid" ]] || continue
        cn=$(svc_cname "$s")
        [[ "$(c_state "$cn")" == running ]] && { sudo docker stop "$cn" >/dev/null || die "could not stop $cn for its ownership handover — stop it by hand and re-run up"; }
        INSPECT_JSON=""
        local d; for d in "$croot/$s" "$cache/$s"; do
            [[ -d "$d" ]] || continue
            sudo chown -R "$uid:$gid" "$d" || die "ownership handover: chown of $d failed — fix it, then re-run up (UID_HANDOVER is kept)"
        done
        # audiobookshelf writes into its media trees (podcast downloads, metadata)
        if [[ "$s" == audiobookshelf ]]; then
            for d in "$media/audiobooks" "$media/podcasts"; do
                [[ -d "$d" ]] || continue
                sudo find "$d" -mindepth 1 -user 0 -exec chown "$uid:$gid" {} + \
                    || die "ownership handover: could not hand over root-owned files in $d — fix it, then re-run up (UID_HANDOVER is kept)"
            done
        fi
        ok "$s: files handed to $uid:$gid"
    done
    state_del UID_HANDOVER
}

provision() {
    hr "Provisioning users, group, folders"
    load_env
    _configure_selfheal   # a service new since the last configure gets its UID before anything starts it
    RENDERED_JSON=""; render
    local gid; gid=$(env_get MEDIA_GROUP_GID 13000)
    getent group mediacenter >/dev/null || { sudo groupadd -g "$gid" mediacenter; ok "group mediacenter ($gid)"; }
    local s v uid croot droot cache tcode
    croot=$(env_get CONFIG_ROOT); droot=$(env_get DATA_ROOT); cache=$(env_get CACHE_ROOT); tcode=$(env_get TRANSCODE_ROOT)
    for s in $(svc_enabled_managed); do
        v="$(uvar "$s")_UID"; uid=$(env_get "$v")
        if [[ -n "$uid" ]] && ! getent passwd "$s" >/dev/null; then
            # no -r: it only warns about our (deliberate) high UIDs; with an
            # explicit -u it contributes nothing that -M and nologin don't.
            sudo useradd -M -s /usr/sbin/nologin -u "$uid" -g mediacenter "$s" \
                && ok "user $s ($uid)" \
                || warn "could not create user $s (uid $uid taken? doctor will flag it)"
        fi
        if [[ $(svc_label "$s" mediastack.config) == "true" ]]; then
            sudo mkdir -p "$croot/$s"
            [[ -n "$uid" ]] && sudo chown "$uid:mediacenter" "$croot/$s"
            # a shard keeps each container's data in its own subfolder of the
            # primary's (authentik: data/, db/, ...): create any missing one
            # owned right, or docker makes it root's and the container cannot write
            local sub m
            while read -r sub; do
                [[ -n "$sub" ]] || continue
                sudo sh -c 'test -e "$1" && exit 0; mkdir -p "$1" && { [ -z "$2" ] || chown "$2:mediacenter" "$1"; }' \
                    _ "$sub" "$uid" </dev/null
            done < <(for m in $(svc_shard "$s"); do
                         jq -r --arg m "$m" --arg p "$croot/$s/" '(.services[$m].volumes // [])[]
                             | select(.type == "bind" and (.source | startswith($p))) | .source' <<<"$RENDERED_JSON"
                     done | sort -u)
        fi
        if [[ $(svc_label "$s" mediastack.cache) == "true" ]]; then
            sudo mkdir -p "$cache/$s"
            [[ -n "$uid" ]] && sudo chown "$uid:mediacenter" "$cache/$s"
        fi
        if [[ $(svc_label "$s" mediastack.transcode) == "true" ]]; then
            sudo mkdir -p "$tcode/$s"
            [[ -n "$uid" ]] && sudo chown "$uid:mediacenter" "$tcode/$s"
        fi
        # Nested bind mounts (e.g. cache inside config): docker creates the
        # inner mountpoint stub as root if missing — pre-create it owned right.
        # Only when MISSING: some services (olivetin) nest *file* mounts under a
        # dir mount, already written by their own installer; mkdir -p there would
        # error ("File exists") or, if the file were absent, create a directory
        # over it and break the mount.
        local stub
        while read -r stub; do
            [[ -z "$stub" ]] && continue
            # One atomic elevated call: test -> create -> own, in a single sudo
            # invocation with detached stdin. Collapsing the previous
            # test/&&/mkdir/chown sequence sidesteps whatever interaction it had
            # with this loop's input stream inside the live provision run (the
            # two-call form skipped existing paths correctly in isolation, but
            # not in situ). Path and uid pass as argv; the body is single-quoted
            # (no interpolation), so the front-door audit stays green.
            sudo sh -c 'test -e "$1" && exit 0; mkdir -p "$1" && { [ -z "$2" ] || chown "$2:mediacenter" "$1"; }' \
                _ "$stub" "$uid" </dev/null
        done < <(jq -r --arg s "$s" '
            (.services[$s].volumes // []) | map(select(.type=="bind")) as $v
            | [ $v[] as $o | $v[] as $i
                | select($i.target != $o.target)
                | select($i.target | startswith($o.target + "/"))
                | $o.source + ($i.target | ltrimstr($o.target)) ]
            | unique | .[]' <<<"$RENDERED_JSON")
    done
    # per-instance data dirs from the label contract
    local dd
    for s in $(svc_enabled_managed); do
        for dd in $(svc_label "$s" mediastack.datadirs); do
            sudo mkdir -p "$droot/$dd"
            sudo chown ":mediacenter" "$droot/$dd"
            sudo chmod 2775 "$droot/$dd"
        done
        # seed the in-app port BEFORE first boot: extra instances share
        # gluetun's namespace, so the image default port would collide
        local ap
        ap=$(svc_label "$s" mediastack.appport)
        if [[ -n "$ap" && ! -f "$croot/$s/config.xml" ]]; then
            printf '<Config>\n  <Port>%s</Port>\n</Config>\n' "$ap" | sudo tee "$croot/$s/config.xml" >/dev/null
            v="$(uvar "$s")_UID"; uid=$(env_get "$v")
            [[ -n "$uid" ]] && sudo chown "$uid:mediacenter" "$croot/$s/config.xml"
            info "$s: seeded in-app port $ap (namespace-shared instance)"
        fi
    done
    # data tree: shared group, setgid so new files inherit it.
    # The recursive pass runs ONLY when the tree root isn't group-correct yet:
    # on a real library this is TBs — never re-walk it on every configure.
    local d
    for sub in tv movies music books other; do sudo mkdir -p "$droot/torrent/$sub"; done
    # media carries the reading/listening trees too (audiobookshelf, kavita);
    # the arr trees take their names from the rootfolder labels (MEDIA_DIR_*)
    for sub in books audiobooks podcasts comics manga other; do
        sudo mkdir -p "$droot/media/$sub"
    done
    local rf
    for s in $(svc_managed); do
        rf=$(svc_label "$s" mediastack.rootfolder)
        [[ -n "$rf" ]] && sudo mkdir -p "$droot/media/${rf##*/}"
    done
    if [[ "$(stat -c %G "$droot" 2>/dev/null)" != mediacenter ]]; then
        info "first-time data tree ownership pass (may take a while on large trees)..."
        sudo chown -R ":mediacenter" "$droot" 2>/dev/null || true
        sudo chmod -R g+rwX "$droot"
        sudo find "$droot" -type d -exec chmod g+s {} +
    fi
    ok "data tree ready (group mediacenter, setgid)"
    sudo mkdir -p "$(env_get BACKUP_ROOT)"
}

reconcile_disabled() {
    # compose does NOT treat profile-disabled services as orphans (verified
    # on compose 5.x): their containers survive `up --remove-orphans`.
    # Remove them explicitly. -v drops their anonymous volumes too.
    render
    local s cn
    # shellcheck disable=SC2046  # service names, one word each
    for s in $(svc_shard $(svc_disabled_managed)); do
        cn=$(svc_cname "$s")
        if [[ $(c_state "$cn") != absent ]]; then
            sudo docker rm -f -v "$cn" >/dev/null; INSPECT_JSON=""
            info "removed container for disabled service: $s"
        fi
    done
}

# ------------------------------------------------------- host port audit --
port_collisions() { # port_collisions [profiles] -> one line per host port published twice
    # Reads the rendered config (the VPN overlay decides who publishes what,
    # so call it after vpn_gen with the render cache cleared). A service is in
    # scope when its name is in COMPOSE_PROFILES — the same test svc_enabled
    # uses; pass a prospective list to check before enabling. gluetun's
    # mappings bind whenever gluetun runs (the overlay publishes every
    # toggle-enabled service through it, enabled or not), so gluetun counts as
    # a whole; each of its mappings is attributed to the namespace-sharing
    # service listening on that target port, so the finding names the app.
    render
    jq -r --arg prof ",${1:-$(env_get COMPOSE_PROFILES)}," '
        .services as $all
        | ($all | to_entries
            | map(select((.value.network_mode // "") == "service:gluetun")
                  | {key: (.value.labels["mediastack.port"] // ""), value: .key})
            | from_entries) as $owner
        | [ $all | to_entries[]
            | .key as $s
            | select($prof | contains("," + $s + ","))
            | .value.ports[]?
            | select((.published // "") != "")
            | { port: "\(.host_ip // "")\(.published)/\(.protocol // "tcp")",
                who:  (if $s == "gluetun" and ($owner[.target|tostring] // "") != ""
                       then "\($owner[.target|tostring]) (via gluetun)" else $s end) } ]
        | group_by(.port) | map(select(length > 1))[]
        | "\(.[0].port): \(map(.who) | join(" and "))"' <<<"$RENDERED_JSON"
}
require_free_ports() { # require_free_ports [profiles]; dies before docker can fail mid-apply
    local found
    found=$(port_collisions "$@") || die "port audit could not evaluate the rendered config — nothing verified (see jq's message above)"
    [[ -z "$found" ]] || die "host port collision — the same port would be published twice:
$(sed 's/^/  /' <<<"$found")
  Docker would refuse the second bind halfway through starting the stack.
  Fix: give one of them a free host port in .env (<SVC>_PORT=…; see docs/adding-a-service.md), then re-run."
}

# ------------------------------------------- up/down/enable/disable/logs --
cmd_up()   {
    load_env
    # vpn_gen FIRST: it reads base + override only, never the overlay, so it
    # always succeeds — and it must run before anything renders, because a
    # stale overlay (a stanza for a service since removed from the override)
    # makes every render fail. Regenerating it here is what makes
    # "disable, delete its block, up" the whole removal procedure.
    vpn_gen
    require_mounts; reconcile_disabled
    require_free_ports
    # label-owned directories BEFORE compose sees them: a missing bind source
    # is created by docker as a root-owned dir, and a service running as its
    # PUID cannot write into that. `enable` and `configure` provision; `up`
    # after an upgrade that added a mount, or after a root moved, did not.
    provision >/dev/null
    uid_handover
    traefik_ensure
    authentik_prepare
    if ! DC up -d --remove-orphans; then
        warn "First start attempt failed — usually gluetun's health race after a recreate."
        info "Waiting for the tunnel (up to ${START_WAIT}s)..."
        wait_verdict --recover gluetun \
            || die "gluetun ${VERDICT_WHY[gluetun]} — nothing VPN'd was started.
  Inspect: ./mediastack.sh logs gluetun (bad credentials? provider outage?)"
        info "Tunnel up — starting the remaining services..."
        DC up -d --remove-orphans
    fi
    vpn_reattach_guard   # fail-closed: no service may run pinned to a dead gluetun
    vpnguard_ensure      # (re)install the boot/daemon guard unit
    svc_enabled authentik && authentik_release_record
    ok "Stack started."
    wire_repoint_pending # a VPN toggle moved a service: re-point what calls it
    cat <<'EOT'
Check on it:   ./mediastack.sh status    (what's running, health, versions)
Verify it:     ./mediastack.sh doctor    (full audit with fixes)
First time? Services need connecting to each other once — the README's
"After install" section walks through it app by app.
EOT
}
cmd_down() {
    load_env
    # --volumes: only anonymous volumes exist in this stack (VOLUME directives
    # in upstream images); all real state is in bind mounts, so this is safe
    # and stops orphaned-volume creep on every stop/start cycle.
    DC down --volumes
    ok "Stack stopped (configs and data untouched)."
}

cmd_enable() {
    local svc="${1:?usage: enable <service>}"; load_env
    svc_exists "$svc" || die "No service '$svc'. Known: $(svc_managed | tr '\n' ' ')"
    svc_enabled "$svc" && { ok "'$svc' already enabled."; return; }
    local c
    for c in $(svc_conflicts "$svc"); do
        svc_enabled "$c" && die "'$svc' and '$c' do the same job two ways and cannot both run:
    $svc — $(svc_label "$svc" mediastack.desc)
    $c — $(svc_label "$c" mediastack.desc)
  Disable '$c' first (./mediastack.sh disable $c), then enable '$svc'."
    done
    local sel cur; cur=$(env_get COMPOSE_PROFILES | tr ',' ' ')
    # shellcheck disable=SC2086  # word splitting intended: service list
    sel=$(resolve_deps "$svc" $cur)
    vpn_gen   # a toggle service enabled for the first time needs its overlay stanza before compose sees it
    RENDERED_JSON=""; require_free_ports "$(echo "$sel" | paste -sd, -)"   # refuse before .env changes
    env_set COMPOSE_PROFILES "$(echo "$sel" | paste -sd, -)"
    require_mounts; provision >/dev/null   # users/dirs for the new services
    uid_handover
    traefik_ensure   # wizard + config gen if traefik just came into the set
    authentik_prepare
    DC up -d --remove-orphans; ok "'$svc' enabled and started."
}
cmd_disable() {
    local svc="${1:?usage: disable <service>}"; load_env
    svc_enabled "$svc" || { ok "'$svc' is not enabled."; return; }
    local e deps blockers=""
    for e in $(env_get COMPOSE_PROFILES | tr ',' ' '); do
        [[ "$e" == "$svc" ]] && continue
        deps=$(svc_deps "$e")
        [[ " $deps " == *" $svc "* ]] && blockers+="$e "
    done
    [[ -n "$blockers" ]] && die "'$svc' is required by enabled service(s): $blockers
  Disable those first, or leave '$svc' running."
    env_set COMPOSE_PROFILES "$(env_get COMPOSE_PROFILES | tr ',' '\n' | grep -vx "$svc" | paste -sd, -)"
    reconcile_disabled
    ok "'$svc' disabled; its container was removed (config kept, still backed up)."
}

cmd_logs() {
    load_env
    # Interactive default follows; --no-follow returns a bounded snapshot, which
    # is what the web front door calls (a following stream would hang the action).
    local svc="" follow=(-f) a
    for a in "$@"; do
        case "$a" in
            --no-follow) follow=() ;;
            -*)          die "unknown option '$a' (usage: logs <service> [--no-follow])" ;;
            *)           [[ -z "$svc" ]] || die "logs takes one service (got '$svc' and '$a')"; svc="$a" ;;
        esac
    done
    [[ -n "$svc" ]] || die "usage: logs <service> [--no-follow]"
    # shellcheck disable=SC2046  # a shard's containers, one word each
    DC logs "${follow[@]}" --tail=100 $(svc_shard "$svc")
}

# ----------------------------------------------------- container inspect --
# Container facts come from `docker inspect` JSON. A reporting command calls
# c_inspect_all once (one privileged call for every managed container) and
# every c_* reads the cache; without it, c_* inspects that one container —
# the same JSON, one call per fact. CACHE RULE: anything that creates,
# recreates, starts, stops or removes a container clears INSPECT_JSON (DC does
# it for every compose verb but config; raw `sudo docker` mutations do it
# explicitly), so a health poll after `up` never reads a stale snapshot.
# A POLLING loop must handle one case itself: a plain read (c_inspect_all in
# another helper) can repopulate the cache between the last mutation and the
# poll, so a loop watching for a state change must re-inspect live each
# iteration. Waiting on container HEALTH: never hand-roll that loop — call
# wait_verdict, which does it (a hand-rolled one shipped this bug twice).
c_inspect() { # c_inspect <cname>... -> JSON array of the containers that exist
    # a missing container is a normal state (before the first `up`); anything
    # else on stderr — daemon down, permission denied — is zero evidence: die
    local err out; err=$(mktemp)
    out=$(sudo docker inspect --type container "$@" 2>"$err") || true
    if grep -vE 'No such (object|container)' "$err" | grep -q .; then
        cat "$err" >&2; rm -f "$err"
        die "docker inspect failed — container state is unverifiable (evidence above)"
    fi
    rm -f "$err"; echo "${out:-[]}"
}
c_inspect_all() { # fill the cache for every managed container and its shard's members (see CACHE RULE)
    render
    local names
    # members too: status and doctor judge a shard by them (found live — left
    # out, a healthy shard read as "degraded", its members as absent)
    names=$(jq -r '.services | to_entries[]
        | select(.value.labels["mediastack.managed"] == "true" or .value.labels["mediastack.shard"] != null)
        | .value.container_name // .key' <<<"$RENDERED_JSON")
    [[ -n "$names" ]] || { INSPECT_JSON="[]"; return 0; }
    # projected to the fields c_get reads: a full inspect of 30 containers is
    # hundreds of KB that every c_* would re-parse — this keeps it to a few
    # shellcheck disable=SC2086  # one name per word
    INSPECT_JSON=$(c_inspect $names | jq -c '[ .[] | {Name, Id, Image, RestartCount,
        State: {Status: .State.Status, StartedAt: .State.StartedAt, Health: .State.Health},
        HostConfig: {NetworkMode: .HostConfig.NetworkMode},
        Config: {User: .Config.User, Labels: {"org.opencontainers.image.version": .Config.Labels["org.opencontainers.image.version"]}},
        Mounts: [ .Mounts[] | {Source, Destination} ] } ]')
}
# ADDING A FIELD TO c_get's READS = ADDING IT TO THE PROJECTION ABOVE, or the
# cached path silently returns "" where the uncached one returns the value.
c_get() { # c_get <cname> <jq path> -> the value, "" when the container is absent
    local j
    if [[ -n "$INSPECT_JSON" ]]; then j=$INSPECT_JSON; else j=$(c_inspect "$1"); fi
    jq -r --arg n "/$1" ".[] | select(.Name == \$n) | $2 // \"\"" <<<"$j"
}
c_state()  { local o; o=$(c_get "$1" '.State.Status'); echo "${o:-absent}"; }
c_health() { local o; o=$(c_get "$1" '.State.Health.Status'); echo "${o:--}"; }
c_uptime() { # human-readable duration since container start (e.g. 3d4h, 12m, 45s)
    # only a running container has an uptime; a stopped one keeps its last
    # StartedAt and a never-started one reports 0001-01-01
    [[ "$(c_state "$1")" == running ]] || { echo "-"; return; }
    local st t sec
    st=$(c_get "$1" '.State.StartedAt')
    if ! t=$(date -d "$st" +%s 2>/dev/null) || (( (sec = $(date +%s) - t) < 0 )); then
        warn "$1: unreadable start time '$st' — uptime shown as ?" >&2
        echo "?"; return
    fi
    if   (( sec >= 86400 )); then echo "$((sec/86400))d$(( (sec%86400)/3600 ))h"
    elif (( sec >= 3600 ));  then echo "$((sec/3600))h$(( (sec%3600)/60 ))m"
    elif (( sec >= 60 ));    then echo "$((sec/60))m$((sec%60))s"
    else echo "${sec}s"; fi
}
c_version(){ c_get "$1" '.Config.Labels["org.opencontainers.image.version"]'; }

c_restarts(){ local o; o=$(c_get "$1" '.RestartCount'); echo "${o:-0}"; }
c_netmode(){ c_get "$1" '.HostConfig.NetworkMode'; }   # "container:<id>" when joined to another namespace
c_id()     { c_get "$1" '.Id'; }
c_host_path() { # c_host_path <cname> <container-path> -> the host path behind it, "" if no mount covers it
    # longest-prefix match over the container's bind mounts; "/x" is not a
    # prefix of "/xy", so the boundary is the mount itself or a "/" after it
    local j
    if [[ -n "$INSPECT_JSON" ]]; then j=$INSPECT_JSON; else j=$(c_inspect "$1"); fi
    jq -r --arg n "/$1" --arg p "$2" '
        [ .[] | select(.Name == $n) | .Mounts[] | . as $m
          | select($m.Destination == $p or ($p | startswith($m.Destination + "/"))) ]
        | sort_by(.Destination | length) | last
        | if . == null then "" else .Source + $p[(.Destination | length):] end' <<<"$j"
}

# Machine-readable service lister — one service name per line, nothing else.
# Built for consumers that need a clean list to parse (e.g. a web UI populating
# a dropdown), and useful on the CLI too. Subsets mirror the sets the other
# verbs accept, so a caller can list exactly the services a given action will
# take. Read-only: renders the config and prints names, changes nothing.

# -------------------------------------------------------- health verdict --
# START_WAIT must exceed every fragment's Docker verdict window,
# start_period + interval x retries (CI: scripts/check-start-wait.sh), so a
# wait only ever cuts off a healthcheck that hangs rather than one that is slow.
START_WAIT=300
VERDICT_BAD=""
declare -A VERDICT_WHY=()
# wait_verdict [--recover] SVC... — block until Docker has judged every
# service, or START_WAIT runs out. The ONE definition of "came up" for every
# wait in the script. A service passes when it is running and healthy — or running with no
# healthcheck and no restart since the call. It fails on unhealthy (Docker's
# own verdict, after the fragment's start_period + retries), on exited, dead
# or absent, or on a restart (boot loop). "starting" keeps it waiting.
# --recover: "unhealthy" is not final either — Docker flips it back on the
# next passing check — for waits whose whole point is riding out a transient
# failure (gluetun re-handshaking after a recreate).
# Prints an OK line per pass; failures are left to the caller's wording in
# VERDICT_BAD (space-separated) and VERDICT_WHY[svc]. Returns 1 on any failure.
# Re-inspects live on every poll (CACHE RULE at c_inspect), whatever the
# caller's cache holds.
wait_verdict() {
    local deadline s cn st h left recover=0
    local -A rc0=() vd=()
    [[ "${1:-}" == --recover ]] && { recover=1; shift; }
    deadline=$(( $(date +%s) + START_WAIT ))
    VERDICT_BAD=""; VERDICT_WHY=()
    INSPECT_JSON=""; c_inspect_all
    for s in "$@"; do rc0[$s]=$(c_restarts "$(svc_cname "$s")"); done
    while :; do
        for s in "$@"; do
            [[ -z "${vd[$s]:-}" ]] || continue
            cn=$(svc_cname "$s"); st=$(c_state "$cn"); h=$(c_health "$cn")
            if (( $(c_restarts "$cn") > rc0[$s] )) || [[ "$st" == restarting ]]; then
                VERDICT_WHY[$s]="is boot-looping (restarted $(c_restarts "$cn") times)"; vd[$s]=bad
            elif [[ "$st" =~ ^(exited|dead|absent)$ ]]; then
                VERDICT_WHY[$s]="is $st"; vd[$s]=bad
            elif [[ "$st" == running && "$h" == unhealthy ]] && (( ! recover )); then
                VERDICT_WHY[$s]="is unhealthy (Docker's verdict)"; vd[$s]=bad
            elif [[ "$st" == running && ( "$h" == healthy || "$h" == "-" ) ]]; then
                ok "$s (running${h:+, }${h/#-/no healthcheck})"; vd[$s]=ok
            fi
        done
        left=0; for s in "$@"; do [[ -n "${vd[$s]:-}" ]] || left=$((left+1)); done
        (( left == 0 )) && break
        (( $(date +%s) < deadline )) || break
        sleep 5
        INSPECT_JSON=""; c_inspect_all
    done
    for s in "$@"; do
        if [[ -z "${vd[$s]:-}" ]]; then
            h=$(c_health "$(svc_cname "$s")")
            VERDICT_WHY[$s]="not healthy after ${START_WAIT}s (health: $h)"
            [[ "$h" == starting ]] && VERDICT_WHY[$s]+=" — its healthcheck is probably hanging"
            vd[$s]=bad
        fi
        [[ "${vd[$s]}" == bad ]] && VERDICT_BAD+="$s "
    done
    VERDICT_BAD=${VERDICT_BAD% }
    [[ -z "$VERDICT_BAD" ]]
}

# ---------------------------------------------------------------- status --
cmd_list() {
    load_env
    # optional --json emits one Olivetin-style entity record per line
    # ({"name":"<svc>"}), for feeding an entity file that backs a UI dropdown.
    # Default is plain names, one per line.
    local json=0 subset="managed" a
    for a in "$@"; do
        case "$a" in
            --json) json=1 ;;
            all|managed|enabled|disabled|vpntoggle|wire|pinned) subset="$a" ;;
            *) die "usage: list [all|managed|enabled|disabled|vpntoggle|wire|pinned] [--json]" ;;
        esac
    done
    local names
    case "$subset" in
        all)        names=$(svc_all | sort) ;;
        managed)    names=$(svc_managed | sort) ;;
        enabled)    names=$(svc_enabled_managed) ;;
        disabled)   names=$(svc_disabled_managed) ;;
        vpntoggle)  render; names=$(jq -r '.services | to_entries[]
                        | select(.value.labels["mediastack.vpntoggle"]=="true") | .key' \
                        <<<"$RENDERED_JSON" | sort) ;;
        wire)       names=$(printf '%s\n' "${WIRE_ROLES[@]}" all) ;;
        pinned)     if [[ -s "$PINS_FILE" ]]; then
                        # service keys are 2-space-indented `  <svc>:`; the image
                        # line is 4-space-indented and won't match.
                        names=$(grep -oE '^  [a-z0-9][a-z0-9-]*:' "$PINS_FILE" | tr -d ' :' | sort || true)
                    else names=""; fi ;;
    esac
    [[ -z "$names" ]] && return 0
    if (( json )); then
        # jq -R reads each raw line; build a safe object (handles any chars).
        printf '%s\n' "$names" | jq -R '{name: .}' -c
    else
        printf '%s\n' "$names"
    fi
}

cmd_status() {
    load_env; render
    if [[ -n "${1:-}" ]]; then status_one "$1"; return; fi
    c_inspect_all
    hr "Mediastack status"
    printf "%-14s %-5s %-5s %-9s %-10s %-12s %-8s %-9s %s\n" SERVICE PORT VPN STATE HEALTH VERSION PINNED UPTIME URL
    local s cn pin vpn port rec bvpn
    bvpn=$(vpn_base_json)   # base (pre-overlay) labels = recommended VPN settings
    for s in $(svc_enabled_managed); do
        cn=$(svc_cname "$s")
        pin=no; [[ -s "$PINS_FILE" ]] && grep -q "^  $s:" "$PINS_FILE" && pin="${C_YLW}yes${C_RST}"
        vpn=off; [[ $(svc_label "$s" mediastack.vpn) == "true" ]] && vpn=on
        [[ "$s" == gluetun ]] && vpn=self   # gluetun IS the tunnel, not behind it
        # flag a toggle-enabled service that's been moved off its recommended setting
        if [[ $(jq -r --arg s "$s" '.services[$s].labels["mediastack.vpntoggle"]//""' <<<"$bvpn") == "true" ]]; then
            rec=$(vpn_onoff "$(jq -r --arg s "$s" '.services[$s].labels["mediastack.vpn"]//"false"' <<<"$bvpn")")
            [[ "$vpn" == "$rec" ]] || vpn+="*"
        fi
        port=$(svc_port "$s"); port=${port:--}
        printf "%-14s %-5s %-5s %-9s %-10s %-12s %-8s %-9s %s\n" \
            "$s" "$port" "$vpn" "$(c_state "$cn")" "$(shard_health "$s")" "$(c_version "$cn" | cut -c1-12)" "$pin" "$(c_uptime "$cn")" "$(svc_url "$s")"
    done
    echo
    info "VPN: on = via the tunnel, off = direct, self = the tunnel itself · * = changed from recommended · change: ./mediastack.sh vpn"
    local off="" p
    for p in $(svc_disabled_managed); do off+="$p "; done
    [[ -n "$off" ]] && info "Available, not enabled: $off"
    local last; last=$(latest_restore_point)
    info "Latest restore point: ${last:-none yet (run: ./mediastack.sh backup)}"
    df -h "$(env_get CONFIG_ROOT)" "$(env_get DATA_ROOT)" 2>/dev/null | tail -n +2 | sort -u \
        | awk '{printf ":: disk %-24s %s used of %s (%s)\n", $6, $3, $2, $5}'
}

status_one() {
    local s="$1"; svc_exists "$s" || die "No service '$s'. Known: $(svc_managed | tr '\n' ' ')"
    local cn st; cn=$(svc_cname "$s")
    INSPECT_JSON=$(c_inspect "$cn")   # one call; every fact below reads it
    st=$(c_state "$cn")
    hr "$s"
    echo "container : $cn"
    echo "state     : $st   health: $(c_health "$cn")"
    echo "image     : $(svc_image "$s")  version: $(c_version "$cn")"
    if [[ "$st" == absent ]]; then
        echo "user      : -"
        echo "restarts  : -"
        echo "mounts    :"
    else
        echo "user      : $(c_get "$cn" '.Config.User')"
        echo "restarts  : $(c_get "$cn" '.RestartCount')"
        echo "mounts    :"
        c_get "$cn" '(.Mounts[] | "  \(.Source) -> \(.Destination)")'
        echo
    fi
    hr "last 15 log lines"
    sudo docker logs --tail 15 "$cn" 2>&1 || true
}



# ------------------------------------------ user-facing (update notices) --
user_facing_list() {
    render; local s tag
    echo "user-facing services — updates notify the household ('users' stream):"
    for s in $(svc_managed); do
        is_user_facing "$s" || continue
        [[ -n "$(env_get "$(uvar "$s")_USER_FACING" "")" ]] && tag=" (override)" || tag=""
        printf '  %s%s\n' "$s" "$tag"
    done
}
# set-user-facing [<svc> true|false] — no args lists the set; otherwise toggles
# whether a service notifies the household on update. Mirrors `vpn`'s idiom: the
# fragment ships the default (mediastack.user_facing), and a ${STEM}_USER_FACING
# line is written to .env ONLY when it deviates (cleared when it matches), so the
# choice is upgrade-safe and no tracked fragment is ever rewritten.
cmd_set_user_facing() {
    load_env
    local svc="${1:-}" act="${2:-}"
    [[ -z "$svc" ]] && { user_facing_list; return; }
    svc_exists "$svc" || die "set-user-facing: no such service '$svc'"
    local target
    case "$act" in
        true|on|yes)  target=true ;;
        false|off|no) target=false ;;
        *) die "usage: ./mediastack.sh set-user-facing [<svc> true|false]" ;;
    esac
    local stem default
    stem=$(uvar "$svc")
    default=$(svc_label "$svc" mediastack.user_facing); default=${default:-false}
    if [[ "$target" == "$default" ]]; then
        env_del "${stem}_USER_FACING"
        ok "set-user-facing: $svc = $target (matches shipped default — override cleared)"
    else
        env_set "${stem}_USER_FACING" "$target"
        ok "set-user-facing: $svc = $target (override stored in .env)"
    fi
}


# ------------------------------------------------------------ dispatcher --

# ---- verb registry ----
# ONE line per verb: verb~usage~args~group~description (~ separates fields; main() dispatches
# usage text may contain |). main() dispatches from it (cmd_<verb>, dashes as
# underscores), the args column is the
# verb's argument contract, and help renders the table — so a verb cannot
# exist without a contract or a help line, and CI checks every verb is
# documented in README (depth lives there; help is one line each).
#   args:  none            no arguments
#          max=N           up to N positional arguments
#          allow=A,B       only these arguments, any order
#          allow=A max=N   both
#          free            the verb parses its own (its `*)` arm dies on unknown input)
#   group: Setup Run Maintain Connect Check Other Internal — Internal verbs
#          exist for the panel, timers and units and are listed last.
VERBS=(
    "help~help~~Other~This list."
    "install~install~none~Setup~Install host dependencies (docker, jq, ...). Run once."
    "configure~configure~none~Setup~Interactive setup wizard: .env, users, folders. Safe to re-run."
    "add-mount~add-mount~none~Setup~Guided NFS/SMB mount on this host (fstab automount + poison layer)."
    "up~up~none~Run~Start the stack (everything enabled in COMPOSE_PROFILES)."
    "down~down~none~Run~Stop the stack. Configs and data are untouched."
    "enable~enable <svc>~max=1~Run~Turn one service on (dependencies come along) and start it."
    "disable~disable <svc>~max=1~Run~Turn one service off (refused while others depend on it)."
    "status~status [svc]~max=1~Run~Overview table of every service, or a deep view of one."
    "logs~logs <svc> [--no-follow]~free~Run~Follow one service's logs (--no-follow: bounded snapshot)."
    "update~update [svc] [--to TAG] [--dry-run|--now]~free~Maintain~Container images: backup, pull, apply (toggles + pins respected)."
    "apply-timer~apply-timer~none~Maintain~Install/refresh the systemd timers from UPDATE_SCHEDULE and MANIFEST_SCHEDULE."
    "backup~backup [verify [TS]]~free~Maintain~Take a restore point now (cold); 'verify' checks checksums and archives."
    "manifest~manifest [--accept|diff [A [B]]|find <text>]~free~Maintain~Snapshot the media library now; 'diff' shows what was lost between snapshots; 'find' says when a path was last seen."
    "restore~restore --service <svc>|--all [--from TS]~free~Maintain~Restore configs + image from a restore point."
    "rollback~rollback <svc>~max=1~Maintain~Restore one service from the newest restore point and pin it there."
    "unpin~unpin <svc>~max=1~Maintain~Release a pinned service back to normal updates."
    "upgrade~upgrade~none~Maintain~Mediastack itself: git pull + .env migration, then says whether up has anything to apply (images stay put: update)."
    "wire~wire [app] [--dry-run|--verify]~free~Connect~Connect the apps to each other; idempotent, GUI changes never overwritten (addresses it made follow VPN toggles)."
    "invite~invite [--expires 1|7|30]~free~Connect~Mint a Wizarr invitation and print the ready-to-share URL."
    "credentials~credentials~none~Connect~Show the app logins wire created/stored."
    "set-credentials~set-credentials <target|all>~max=1~Connect~Rotate a stored login everywhere it lives, atomically."
    "notify~notify [status|test [stream]|set <stream>|clear <stream>|send <stream> <title> <message> [--type T]]~free~Connect~Notification streams (ops, users): status, test, change or clear a stream's URLs, send your own message."
    "set-user-facing~set-user-facing [<svc> true|false]~max=2~Connect~Show or change which services notify the household on update (the 'users' stream)."
    "traefik-setup~traefik-setup [--hosts|--certs]~allow=--hosts,--certs max=1~Connect~Configure the HTTPS edge (domain, token, staging/production, dashboard login)."
    "trash-sync~trash-sync [--dry-run]~allow=--dry-run~Connect~Sync TRaSH Guides quality profiles to the arrs (--dry-run previews drift)."
    "doctor~doctor~none~Check~Full health/permission/port/backup audit; every failure states its fix."
    "audit~audit [status|on|off|report [--since DATE] [--path TEXT]]~free~Check~Deletion attribution (opt-in): who deleted or renamed media; 'report' reads the history, 'status' proves it live."
    "leak-test~leak-test [--killswitch]~allow=--killswitch~Check~Prove no VPN'd service can leak (--killswitch: disruptive tunnel-drop proof)."
    "vpn~vpn [svc on|off] [--i-know]~max=3~Check~Show or change which services run behind the VPN; apply with: up."
    "fix-perms~fix-perms [svc]~max=1~Check~Repair ownership of a service's config/cache/transcode folders from the UID map."
    "new-service~new-service <name>~max=1~Other~Add your own service: asks image/port/VPN/folders, then enables and starts it."
    "frontdoor-install~frontdoor-install [--set-password]~allow=--set-password~Other~Install the OliveTin web panel over the safe verbs."
    "uninstall~uninstall [--nuke]~allow=--nuke~Other~Remove the stack (tiered; --nuke: one confirmed shot). Media and backups are never touched."
    "menu~menu~none~Other~Interactive menu wrapping the common verbs."
    "list~list [--json]~free~Internal~Enabled services, one per line (--json: panel entity records)."
    "vpn-apply~vpn-apply <svc> on|off~max=2~Internal~Set a service's VPN membership AND apply it (panel button)."
    "vpn-guard~vpn-guard [--boot]~allow=--boot~Internal~Re-pin VPN dependents onto the live gluetun (boot/daemon unit)."
    "frontdoor-refresh~frontdoor-refresh~none~Internal~Regenerate the panel's config and entity files."
    "audit-extract~audit-extract~none~Internal~Copy new deletion events from auditd's rotating log into the durable log (hourly timer)."
)

verb_entry() { # verb_entry <verb> -> its registry line, rc 1 if unknown
    local e; for e in "${VERBS[@]}"; do [[ "${e%%~*}" == "$1" ]] && { echo "$e"; return 0; }; done; return 1
}

# ---- argument discipline ----
# Every verb declares what it accepts; anything else is rejected before it
# runs, so a typo or an unsupported flag never silently falls through to the
# default behaviour (e.g. 'trash-sync --dry-run' once ran a real sync).
CMD=""
args_none()  { (( $# == 0 )) || die "'$CMD' takes no arguments (got: $*)"; }
args_max()   { local n="$1"; shift; (( $# <= n )) || die "'$CMD' takes at most $n argument(s) (got: $*)"; }
args_allow() { # args_allow "<space-separated allowed args>" "$@" — anything else is rejected
    local allowed="$1" a; shift
    for a in "$@"; do [[ " $allowed " == *" $a "* ]] || die "unknown argument '$a' for '$CMD' (accepts: ${allowed:-nothing})"; done
    return 0
}
args_check() { # args_check "<args column>" "$@" — apply a registry contract
    local spec="$1" tok; shift
    for tok in $spec; do
        case "$tok" in
            none)    args_none "$@" ;;
            free)    ;;
            max=*)   args_max "${tok#max=}" "$@" ;;
            allow=*) tok=${tok#allow=}; args_allow "${tok//,/ }" "$@" ;;
            *)       die "registry: unknown args token '$tok' for '$CMD'" ;;
        esac
    done
}

main() {
    local cmd="${1:-help}"; shift || true
    case "$cmd" in -h|--help) cmd=help ;; esac
    CMD="$cmd"
    local entry
    entry=$(verb_entry "$cmd") || { fail "Unknown command '$cmd'"; echo; cmd_help; exit 1; }
    local spec; spec=$(cut -d'~' -f3 <<<"$entry")
    args_check "$spec" "$@"
    "cmd_${cmd//-/_}" "$@"
}

main "$@"
