#!/usr/bin/env bash
# lib/audit.sh — deletion attribution (opt-in). The kernel's audit system logs
# every successful delete and rename under the media root — the manifest's
# scope: the manifest says WHAT went missing, this says WHO — with the UID
# that made the call. Each service runs as its own *_UID, so the UID names the
# service; a person is named by their login UID, which survives sudo. Holds
# cmd_audit (status|on|off), the teardown uninstall uses, and the doctor
# section. Sourced by the entrypoint; relies on lib/common.sh, lib/doctor.sh
# (d_fail) and lib/manifest.sh (manifest_root) at call time.
#
# A host feature, not a container: the kernel keeps one audit rule set and one
# audit daemon per host, not per container (docs/watchlist.md). Outside the
# repo it owns exactly AUDIT_FOOTPRINT, plus the auditd package when it was
# the one to install it — recorded in the rules file itself, so no separate
# state exists to drift. auditd's own settings (auditd.conf; -b, -f, -e) are
# never written: on a fresh install the package defaults stand, on a host
# that already ran auditd they are the operator's. doctor reports on them.

AUDIT_KEY=mediastack-media
# 99-: loads after every other rules file, so an error in it cannot keep
# anyone else's rules from loading at boot
AUDIT_RULES=/etc/audit/rules.d/99-mediastack.rules
AUDIT_SYSCALLS=unlink,unlinkat,rename,renameat,renameat2,rmdir
AUDIT_LOGDIR=/var/log/audit   # the package's; removed with it only when mediastack installed it
AUDIT_MARK="# mediastack-installed-auditd:"
# every path this feature puts outside the repo (the shared host-footprint
# registry planned in docs/roadmap.md → Structure will collect these lists)
AUDIT_FOOTPRINT=("$AUDIT_RULES")

audit_root() { # the watched tree, canonical; rc 1 when it does not exist
    realpath -e "$(manifest_root)" 2>/dev/null
}

audit_rules_render() { # audit_rules_render ROOT yes|no -> the rules file; same inputs, same bytes
    printf '%s\n' \
        "# Generated by mediastack.sh — do not edit. Rewrite: ./mediastack.sh audit on   Remove: ./mediastack.sh audit off" \
        "# Watch rules only: auditd's own settings (buffers, failure mode, lock) are never set here." \
        "$AUDIT_MARK $2"
    local arch
    for arch in b64 b32; do
        # success=1: NFS refuses renameat2 and callers retry with renameat —
        # the refused attempt is not a deletion, so the kernel drops it here
        printf -- '-a always,exit -F arch=%s -S %s -F dir=%s -F success=1 -k %s\n' \
            "$arch" "$AUDIT_SYSCALLS" "$1" "$AUDIT_KEY"
    done
}

# auditctl lives in /usr/sbin: on root's PATH (sudo's secure_path), not on
# the operator's — every presence check asks root, like every call does
audit_have() { sudo sh -c 'command -v auditctl' >/dev/null 2>&1; }

audit_rules_present() { sudo test -e "$AUDIT_RULES"; }

audit_marker() { # yes|no from the rules file header; empty when there is no file
    audit_rules_present || return 0
    sudo sed -n "s/^$AUDIT_MARK //p" "$AUDIT_RULES"
}

audit_stat_field() { # audit_stat_field FIELD < `auditctl -s` output -> its value
    awk -v k="$1" '$1 == k { print $2 }'
}
audit_stat() { sudo auditctl -s | audit_stat_field "$1"; }

audit_loaded() { # the loaded rules carrying our key, one per line
    audit_have || return 0
    sudo auditctl -l | grep -F -- "key=$AUDIT_KEY" || true   # none loaded is a valid answer
}
audit_loaded_count() { audit_loaded | grep -c . || true; }   # grep -c exits 1 on zero

audit_uid_dupes() { # the *_UID values .env gives to more than one service, space-separated
    { grep -E '^[A-Z0-9_]+_UID=[0-9]+$' "$ENV_FILE" || true; } | cut -d= -f2 | sort | uniq -d | tr '\n' ' '   # no UIDs set: nothing shared
}

audit_canary() { # prove the watch fires: create and delete a file in the media root, find the delete in the log
    local root f gid n
    root=$(audit_root) || return 1
    gid=$(getent group mediacenter | cut -d: -f3)
    [[ -n "$gid" ]] || return 1
    f="$root/.mediastack-audit-canary-$(date +%s%N)"
    # as the repo's owner in the media group, not root: an NFS share squashes
    # root, the operator's UID writes like any service does
    sudo setpriv --reuid="$(stat -c %u "$SCRIPT_DIR")" --regid="$gid" --clear-groups touch "$f" || return 1
    sudo setpriv --reuid="$(stat -c %u "$SCRIPT_DIR")" --regid="$gid" --clear-groups rm "$f" || return 1
    for n in 1 2 3 4 5; do   # auditd writes asynchronously
        sudo ausearch -k "$AUDIT_KEY" -ts recent -f "$f" >/dev/null 2>&1 && return 0
        sleep "$n"
    done
    return 1
}

cmd_audit() {
    case "${1:-status}" in
        status) audit_status ;;
        on)     audit_on ;;
        off)    audit_off ;;
    esac
}

audit_status() {
    load_env
    _doctor_audit
    echo
    (( D_FAILS )) && { fail "audit: $D_FAILS problem(s) — fixes listed above."; exit 1; }
    ok "audit: all checks passed."
}

audit_on() {
    load_env
    [[ "$(uname -m)" == x86_64 ]] || die "audit supports x86_64 hosts only so far (this one is $(uname -m)):
  the syscalls it watches have different names on other architectures."
    local root mark
    root=$(audit_root) || die "the media root $(manifest_root) does not exist.
  Run ./mediastack.sh up once (it creates the tree), then retry."
    [[ "$root" =~ [[:space:]] ]] && die "the media root '$root' contains whitespace, which an audit rule cannot express.
  Move DATA_ROOT (./mediastack.sh configure), then retry."
    mark=$(audit_marker)
    if ! audit_have; then
        command -v apt-get >/dev/null 2>&1 || die "'audit on' installs auditd with apt, and this host has no apt.
  Install auditd with your package manager, then re-run — it is then treated as yours."
        info "Installing auditd..."
        sudo apt-get update -qq
        sudo apt-get install -y -qq auditd >/dev/null || die "apt could not install auditd (its error is above)."
        mark=yes
    elif [[ -z "$mark" ]]; then
        mark=no
        warn "auditd is already set up on this host — that setup is yours and stays untouched."
        echo "  'audit on' adds one file, $AUDIT_RULES, holding only watch rules"
        echo "  for $root. auditd.conf and your own rules are not changed; 'audit off'"
        echo "  removes the file again."
        confirm "Add mediastack's watch rules to your auditd?" || { info "Nothing changed."; return 0; }
    fi
    systemctl is-active --quiet auditd || die "auditd is installed but not running.
  Start it: sudo systemctl enable --now auditd — then retry."
    local en; en=$(audit_stat enabled)
    case "$en" in
        1) ;;
        2) die "the kernel's audit rules are locked (auditctl -s: enabled 2, from an '-e 2' rule).
  Nothing can be added until a reboot: remove the lock or reboot, then retry." ;;
        *) die "kernel auditing is off (auditctl -s: enabled ${en:-unreadable}) — usually audit=0 on the kernel command line.
  Remove it, reboot, then retry." ;;
    esac
    local tmp; tmp=$(mktemp)
    audit_rules_render "$root" "$mark" > "$tmp"
    sudo install -m 0640 -o root -g root "$tmp" "$AUDIT_RULES"
    rm -f "$tmp"
    # load only ours, straight from the file: the operator's live rules are
    # never reloaded; a re-run replaces ours (the key selects them)
    (( $(audit_loaded_count) == 0 )) || sudo auditctl -D -k "$AUDIT_KEY" >/dev/null
    local out
    out=$(sudo auditctl -R "$AUDIT_RULES" 2>&1) || die "auditctl refused $AUDIT_RULES:
$(sed 's/^/  /' <<<"$out")"
    (( $(audit_loaded_count) == 2 )) || die "auditctl accepted $AUDIT_RULES but the kernel holds $(audit_loaded_count) of its 2 rules:
$(audit_loaded | sed 's/^/  /')"
    env_set AUDIT_ENABLED true
    audit_canary || die "the rules are loaded, but a test delete in $root was not logged.
  Look for it: sudo ausearch -k $AUDIT_KEY -ts recent — then run: ./mediastack.sh audit status"
    ok "deletion attribution on: every delete and rename under $root is logged with who made it"
    info "a test delete was made and found in the log (live proof)"
}

audit_off() {
    load_env
    audit_teardown ask
    env_set AUDIT_ENABLED false
}

audit_teardown() { # audit_teardown ask|yes — remove the footprint; needs no .env (nuke calls it)
    local mark; mark=$(audit_marker)
    if [[ -z "$mark" ]] && (( $(audit_loaded_count) == 0 )); then
        info "deletion attribution is not set up on this host — nothing to remove."
        return 0
    fi
    (( $(audit_loaded_count) == 0 )) || sudo auditctl -D -k "$AUDIT_KEY" >/dev/null
    (( $(audit_loaded_count) == 0 )) || die "auditctl kept $(audit_loaded_count) rule(s) with key $AUDIT_KEY:
$(audit_loaded | sed 's/^/  /')"
    sudo rm -f "${AUDIT_FOOTPRINT[@]}"
    ok "watch rules unloaded; removed ${AUDIT_FOOTPRINT[*]}"
    [[ "$mark" == yes ]] || return 0
    # the package came from 'audit on': offer it back, unless someone else
    # has started using it since (another rules file beside the package's)
    local others
    others=$(sudo find "${AUDIT_RULES%/*}" -maxdepth 1 -name '*.rules' ! -name audit.rules -printf '%f ')
    if [[ -n "$others" ]]; then
        warn "auditd was installed by mediastack, but other rules now use it ($others) — kept."
        return 0
    fi
    if [[ "$1" == ask ]] && ! confirm "mediastack installed auditd. Remove it too, with its logs in $AUDIT_LOGDIR?"; then
        info "auditd kept — from now on it counts as yours."
        return 0
    fi
    sudo apt-get purge -y -qq auditd >/dev/null || die "apt could not remove auditd (its error is above)."
    sudo rm -rf "$AUDIT_LOGDIR"
    ok "auditd and its logs removed"
}

# ------------------------------------------------------------------ doctor --
_doctor_audit() {
    hr "doctor: deletion attribution"
    if [[ "$(env_get AUDIT_ENABLED false)" != true ]]; then
        local left=""
        audit_rules_present && left+="$AUDIT_RULES "
        (( $(audit_loaded_count) > 0 )) && left+="loaded rules (key $AUDIT_KEY) "
        if [[ -n "$left" ]]; then
            d_fail "off, but its pieces remain: ${left% }" "they keep logging deletes nobody reads, and would outlive an uninstall" \
                "./mediastack.sh audit off"
        else
            info "off (opt in: ./mediastack.sh audit on)"
        fi
        return 0
    fi
    if ! audit_have; then
        d_fail "AUDIT_ENABLED=true but auditd is not installed" "no deletion is recorded" "./mediastack.sh audit on"
        return 0
    fi
    systemctl is-active --quiet auditd && ok "auditd running" \
        || d_fail "auditd is not running" "deletions are not written anywhere" "sudo systemctl enable --now auditd"
    local root
    if ! root=$(audit_root); then
        d_fail "the media root $(manifest_root) does not exist" "there is nothing to watch" "./mediastack.sh up (creates the tree)"
        return 0
    fi
    if ! audit_rules_present; then
        d_fail "$AUDIT_RULES is missing" "the watch is gone after the next reboot" "./mediastack.sh audit on"
    elif [[ "$(sudo cat "$AUDIT_RULES")" != "$(audit_rules_render "$root" "$(audit_marker)")" ]]; then
        d_fail "$AUDIT_RULES does not match this install (the media root moved, or it was edited)" \
            "deletes are watched in the wrong place" "./mediastack.sh audit on"
    else
        ok "rules file current (watching $root)"
    fi
    local n; n=$(audit_loaded | grep -cF -- "dir=$root " || true)   # zero matches is the finding, not an error
    (( n == 2 )) && ok "watch rules loaded" \
        || d_fail "$n of 2 watch rules for $root are loaded" "deletes are not being recorded" "./mediastack.sh audit on"
    _doctor_audit_kernel
    case "$(fstype_of "$root")" in
        cifs|smb3) warn "the media root is on SMB: deletion watching is proven on local disks and NFS only" ;;
    esac
    audit_canary && ok "live check: a test delete in $root was logged" \
        || d_fail "live check: a test delete in $root was NOT logged" \
            "the watch does not see this filesystem (remounted since the rules loaded?), or the operator cannot write there" \
            "./mediastack.sh audit on, then re-check; evidence: sudo ausearch -k $AUDIT_KEY -ts recent"
    local dup; dup=$(audit_uid_dupes)
    [[ -z "$dup" ]] && ok "every service runs as its own UID" \
        || d_fail "UIDs shared by more than one service in .env: ${dup% }" "a delete by that UID cannot be pinned to one service" \
            "give each service its own *_UID in .env, then: ./mediastack.sh up && ./mediastack.sh fix-perms"
    return 0
}

_doctor_audit_kernel() { # the kernel's audit settings: reported, never changed (they may be the operator's)
    local s lost bl fm
    if ! s=$(sudo auditctl -s 2>&1); then
        warn "auditctl -s failed, kernel audit settings UNCONFIRMED: $s"
        return 0
    fi
    lost=$(audit_stat_field lost <<<"$s"); bl=$(audit_stat_field backlog_limit <<<"$s"); fm=$(audit_stat_field failure <<<"$s")
    (( ${lost:-0} > 0 )) && warn "the kernel dropped $lost audit events since boot (any key, not only mediastack's) — raise the backlog (-b) in /etc/audit/rules.d"
    (( ${bl:-0} < 8192 )) && warn "audit backlog is ${bl:-unreadable} events: a bulk import or mass delete can overflow it (8192+ recommended; -b in /etc/audit/rules.d)"
    [[ "$fm" == 2 ]] && warn "audit failure mode is 2: the kernel PANICS if auditing fails (1 logs and carries on) — this host's setting, not mediastack's"
    return 0
}
