#!/usr/bin/env bash
# lib/trash.sh — `trash-sync`: TRaSH Guides quality profiles via Recyclarr —
# instance selection, config generation, ownership banners and the sync run.
# Sourced by the entrypoint; relies on lib/common.sh, lib/integrations.sh (arr
# API helpers, http_ready, wfail) and the entrypoint's helpers at call time.

# =================================================================== trash --
# Wave 2: TRaSH Guides sync via Recyclarr (guide-backed profiles, v8 schema).
# Managed instances: sonarr, sonarr-anime, radarr, radarr-4k. Lidarr is out
# of scope (recyclarr supports sonarr/radarr only).

trash_instances() {
    local s; for s in sonarr sonarr-anime radarr radarr-4k; do
        svc_enabled "$s" || continue
        echo "$s"
    done
}

trash_envkey() { echo "TRASH_PROFILE_$(tr 'a-z-' 'A-Z_' <<<"$1")"; }

# profile menu: stored once in .env; radarr-4k and sonarr-anime pre-answered
trash_menu() {
    local s key cur
    for s in $(trash_instances); do
        key=$(trash_envkey "$s"); cur=$(env_get "$key")
        [[ -n "$cur" ]] && continue
        case "$s" in
            radarr-4k)    env_set "$key" uhd;   info "radarr-4k: pre-answered 'uhd' (that is its whole job)"; continue ;;
            sonarr-anime) env_set "$key" anime; info "sonarr-anime: pre-answered 'anime'"; continue ;;
        esac
        if [[ ! -t 0 ]]; then
            env_set "$key" skip
            warn "$s: no TRaSH profile chosen and no terminal to ask — set to 'skip'; run './mediastack.sh trash-sync' interactively to choose"
            continue
        fi
        explain "TRaSH profile: $s" \
"Pick the quality profile recyclarr will manage on this instance.
  1) 1080p   TRaSH guide default (recommended)
  2) 720p    space saver (ours: smaller grabs, WEB-preferred)
  3) 4k      TRaSH UHD guide profile
  4) skip    leave this instance unmanaged"
        ask TP "Choice for $s [1080p/720p/4k/skip]" "1080p"
        case "$REPLY_VAL" in
            1080p|720p|4k|skip) env_set "$key" "$REPLY_VAL" ;;
            *) die "Unknown choice '$REPLY_VAL' — expected 1080p, 720p, 4k or skip." ;;
        esac
    done
}

# our 720p space-saver profile (full custom profile; recyclarr replaces
# qualities wholesale, so the list must be complete)
trash_720p_profile() { # $1 = sonarr|radarr
    cat <<'Y720'
      - name: "[synced] 720p Space Saver"
        reset_unmatched_scores:
          enabled: true
        upgrade:
          allowed: true
          until_quality: WEB 720p
          until_score: 10000
        min_format_score: 0
        quality_sort: top
        qualities:
          - name: WEB 720p
            qualities: [WEBDL-720p, WEBRip-720p]
          - name: Bluray-720p
          - name: HDTV-720p
Y720
}

# verbatim splice of the user's score overrides for one instance.
# local/trash-overrides.yml sections are native recyclarr custom_formats
# lists under a top-level "<service>:" key — see docs/trash-sync.md.
trash_overrides_for() { # $1 = svc; emits indented custom_formats block
    local f=local/trash-overrides.yml
    [[ -s "$f" ]] || return 0
    awk -v svc="$1" '
        /^[a-z0-9-]+:[[:space:]]*$/ { insec = ($0 == svc":") ; next }
        insec && /^[[:space:]]/ { print }
        insec && /^[^[:space:]#]/ { insec = 0 }
    ' "$f"
}

# dedicated system user for the recyclarr container: same pattern as every
# service (uid from .env, primary group mediacenter — which is also how nuke
# finds and removes it). trash-sync self-provisions so configure isn't needed.
trash_provision() {
    local uid gid
    uid=$(env_get RECYCLARR_UID 13020); gid=$(env_get MEDIA_GROUP_GID 13000)
    env_set RECYCLARR_UID "$uid"
    if ! getent group mediacenter >/dev/null; then
        sudo groupadd -g "$gid" mediacenter && ok "group mediacenter ($gid)" \
            || { wfail "could not create group mediacenter"; return 1; }
    fi
    if ! getent passwd recyclarr >/dev/null; then
        sudo useradd -M -s /usr/sbin/nologin -u "$uid" -g mediacenter recyclarr \
            && ok "user recyclarr ($uid)" \
            || { wfail "could not create user recyclarr (uid $uid taken?)"; return 1; }
    fi
    # one-time cleanup: an earlier fragment used an include-relative mount
    # path, which docker auto-created root-owned under compose.d/
    [[ -d compose.d/local ]] && sudo rm -rf compose.d/local
    sudo install -d -o "$uid" -g mediacenter -m 750 "$(env_get CONFIG_ROOT)/recyclarr"
    ok "recyclarr user ($uid) + config dir ready"
}

trash_gen_config() { # trash_gen_config [out-path] — default: the live recyclarr.yml
    local uid out tmp
    uid=$(env_get RECYCLARR_UID 13020)
    out="${1:-$(env_get CONFIG_ROOT)/recyclarr/recyclarr.yml}"
    tmp=$(mktemp)
    {
        echo "# GENERATED by mediastack trash-sync — DO NOT EDIT."
        echo "# Choices live in .env (TRASH_PROFILE_*); score overrides in"
        echo "# local/trash-overrides.yml. Regenerated on every trash-sync run."
        echo "# yaml-language-server: \$schema=https://schemas.recyclarr.dev/v8/config-schema.json"
    } > "$tmp"
    local s key choice app port apikey ov n
    local wrote_sonarr=0 wrote_radarr=0
    for s in $(trash_instances); do
        key=$(trash_envkey "$s"); choice=$(env_get "$key")
        [[ -z "$choice" || "$choice" == skip ]] && continue
        app=$(svc_label "$s" mediastack.arrtype)   # sonarr | radarr
        port=$(svc_label "$s" mediastack.port)
        apikey=$(arr_key "$s")
        [[ -n "$apikey" ]] || { wfail "$s: no ApiKey yet — start it, then re-run trash-sync"; continue; }
        if [[ "$app" == sonarr && $wrote_sonarr == 0 ]]; then echo "sonarr:" >> "$tmp"; wrote_sonarr=1; fi
        if [[ "$app" == radarr && $wrote_radarr == 0 ]]; then echo "radarr:" >> "$tmp"; wrote_radarr=1; fi
        {
            echo "  $s:"
            echo "    base_url: http://localhost:$port"
            echo "    api_key: $apikey"
            case "$app/$choice" in
                sonarr/anime) echo "    quality_definition: {type: anime}" ;;
                sonarr/*)     echo "    quality_definition: {type: series}" ;;
                radarr/*)     echo "    quality_definition: {type: movie}" ;;
            esac
            echo "    quality_profiles:"
            case "$app/$choice" in
                sonarr/1080p) echo '      - trash_id: 72dae194fc92bf828f32cde7744e51a1  # WEB-1080p'
                              printf '%s\n' '        name: "[synced] WEB-1080p"' '        reset_unmatched_scores:' '          enabled: true' ;;
                sonarr/4k)    echo '      - trash_id: d1498e7d189fbe6c7110ceaabb7473e6  # WEB-2160p'
                              printf '%s\n' '        name: "[synced] WEB-2160p"' '        reset_unmatched_scores:' '          enabled: true' ;;
                sonarr/anime) echo '      - trash_id: 20e0fc959f1f1704bed501f23bdae76f  # [Anime] Remux-1080p'
                              printf '%s\n' '        name: "[synced] Anime Remux-1080p"' '        reset_unmatched_scores:' '          enabled: true' ;;
                radarr/1080p) echo '      - trash_id: d1d67249d3890e49bc12e275d989a7e9  # HD Bluray + WEB'
                              printf '%s\n' '        name: "[synced] HD Bluray + WEB"' '        reset_unmatched_scores:' '          enabled: true' ;;
                radarr/uhd|radarr/4k)
                              echo '      - trash_id: 64fb5f9858489bdac2af690e27c8f42f  # UHD Bluray + WEB'
                              printf '%s\n' '        name: "[synced] UHD Bluray + WEB"' '        reset_unmatched_scores:' '          enabled: true' ;;
                */720p)       trash_720p_profile "$app" ;;
                *) die "unmapped profile choice '$choice' for $s (env $key)" ;;
            esac
        } >> "$tmp"
        ov=$(trash_overrides_for "$s")
        if [[ -n "$ov" ]]; then
            n=$(grep -c 'trash_ids:' <<<"$ov" || true)
            printf '%s\n' "$ov" >> "$tmp"
            ok "$s: profile '$choice' ($n overridden)"
        else
            ok "$s: profile '$choice'"
        fi
    done
    sudo install -o "$uid" -g mediacenter -m 600 "$tmp" "$out" && rm -f "$tmp" \
        || { rm -f "$tmp"; wfail "could not install $out"; return 1; }
}

# the ownership banner: a never-matching CF that sorts first in the GUI so
# nobody hand-tunes what nightly sync will revert. Recyclarr cannot create
# non-TRaSH CFs, so we push it ourselves (idempotent by name).
# container "running" is not API "ready" — after a cold restart the arrs
# answer errors for a few seconds. Poll each instance before touching it.
arr_api_ready() { # arr_api_ready <svc> <shared-deadline-epoch> -> 0 ready
    local key; key=$(arr_key "$1")
    [[ -n "$key" ]] || { wfail "$1: no API key readable from its config — is it initialised? (./mediastack.sh wire arr)"; return 1; }
    http_ready --until "$2" "$1" "$(arr_url "$1")/api/$(arr_apiver "$1")/system/status" '^200$' -H "X-Api-Key: $key"
}

TRASH_SENTINEL='[!] Synced by mediastack — tune via local/trash-overrides.yml'
trash_sentinel() { # $1 = svc
    local s="$1" key url cur
    key=$(arr_key "$s") || true; [[ -n "$key" ]] || return 0
    url=$(arr_url "$s")
    cur=$(api GET "$url/api/$(arr_apiver "$s")/customformat" "$key" || true)
    if jq -e --arg n "$TRASH_SENTINEL" 'any(.[]; .name == $n)' <<<"$cur" >/dev/null 2>&1; then
        ok "$s: sentinel banner present"
    elif w_would "$s: create sentinel banner custom format"; then
        local sresp
        if sresp=$(api POST "$url/api/$(arr_apiver "$s")/customformat" "$key" "$(jq -nc --arg n "$TRASH_SENTINEL" \
            '{name:$n, includeCustomFormatWhenRenaming:false, specifications:[{name:"Never matches", implementation:"ReleaseTitleSpecification", negate:false, required:true, fields:[{name:"value", value:"\\b\\B"}]}]}')"); then
            ok "$s: sentinel banner created"
        else
            wfail "$s: sentinel creation rejected — API said: $(head -c160 <<<"$sresp")"
        fi
    fi
}

# condense recyclarr's sync log into one line for doctor + the verdict.
# recyclarr only renders its results table on a TTY; captured output is
# plain [INF] logging, so that is what we parse: "Created/Updated/Deleted
# N <thing>" lines per instance mean drift was repaired or guides moved.
# Best-effort: unrecognized output degrades to a note, never the verdict.
trash_summarize() { # $1 = captured sync log
    awk '
        /^\[INF\] [a-z0-9-]+: (Created|Updated|Deleted) [0-9]+ / {
            name=$2; sub(/:$/, "", name)
            detail=""; for (i=3; i<=NF; i++) detail = detail (detail?" ":"") $i
            sub(/:.*/, "", detail)
            per[name] = per[name] (per[name] ? ", " : "") detail
        }
        /^\[INF\] [a-z0-9-]+: Processing / { rows++ }
        END {
            if (rows == 0) { print "summary unavailable (unrecognized output)"; exit }
            out=""
            for (n in per) out = out (out ? " " : "") n "(" per[n] ")"
            if (out == "") print "all in sync, no drift"
            else           print "changes applied: " out
        }
    ' "$1"
}

trash_preview_summarize() { # $1 = captured `sync --preview` log -> "<count>|<summary>"
    # preview renders one "── <pipeline> (Preview) [<instance>] ──" block per
    # pipeline per instance, each followed by "No changes" or a change table.
    # Counts the pipelines that would change; the caller adds that to
    # WIRE_CHANGES (this runs inside $(...), so it cannot do so itself).
    # a pty emits ANSI colour and CRLF line endings: strip both before matching
    sed -e 's/\x1b\[[0-9;?]*[A-Za-z]//g' -e 's/\r$//' "$1" | awk '
        /^── .* \(Preview\) \[[a-z0-9-]+\] ──/ { blocks++; open=1; name=$0; sub(/.*\[/, "", name); sub(/\].*/, "", name); next }
        open && /^No changes/ { open=0; next }
        open && NF { drift++; open=0; per[name]++ }
        END {
            out=""; for (i in per) out = out (out ? " " : "") i "(" per[i] ")"
            if (blocks == 0)     print "0|FAIL"   # nothing rendered: drift is UNKNOWN, not zero
            else if (drift == 0) print "0|all in sync, no drift (" blocks " pipeline blocks checked)"
            else                 print drift "|would change: " out " (pipelines per instance)"
        }'
}

# shellcheck disable=SC2120  # arguments arrive via main()'s registry dispatch
cmd_trash_sync() { # trash-sync [--dry-run]
    WIRE_FAILS=0; WIRE_CHANGES=0; WIRE_DRY=0
    [[ "${1:-}" == --dry-run ]] && WIRE_DRY=1
    local insts s rdir live preview
    if (( WIRE_DRY )); then
        hr "trash-sync --dry-run: previewing drift, touching nothing"
    else
        hr "trash-sync: TRaSH Guides via Recyclarr"
    fi
    insts=$(trash_instances)
    [[ -n "$insts" ]] || { info "no managed arr instances enabled — nothing to sync"; return 0; }
    wire_gate $insts
    rdir="$(env_get CONFIG_ROOT)/recyclarr"; live="$rdir/recyclarr.yml"; preview="$rdir/recyclarr.preview.yml"
    if (( WIRE_DRY )); then
        # a preview needs a provisioned recyclarr and answered profile choices:
        # both are decisions the real run makes, and a dry run makes none
        sudo test -d "$rdir" || die "recyclarr is not provisioned yet — run './mediastack.sh trash-sync' once, then preview"
        # recyclarr renders its preview with Spectre.Console and discards ALL of
        # that when its stdout is not a TTY (its "log mode"); the run below
        # forces a pty, which needs a terminal on our stdin to attach
        [[ -t 0 ]] || die "trash-sync --dry-run needs a terminal (recyclarr only renders a preview on a TTY)"
        for s in $insts; do
            [[ -n "$(env_get "$(trash_envkey "$s")")" ]] \
                || die "$s: no TRaSH profile chosen yet — run './mediastack.sh trash-sync' once to choose, then preview"
        done
        hr "trash-sync: generate config (preview copy)"
        # the generated config goes to a scratch file beside the live one; the
        # preview syncs from it so the diff being previewed is the real one
        trash_gen_config "$preview"
        if sudo cmp -s "$live" "$preview" 2>/dev/null; then
            ok "recyclarr.yml unchanged"
        else
            w_would "install the regenerated recyclarr.yml (differs from the live one)" || true
        fi
    else
        trash_menu
        hr "trash-sync: provision"
        trash_provision || { fail "trash-sync aborted: provisioning failed."; return 1; }
        hr "trash-sync: generate config"
        trash_gen_config
    fi
    hr "trash-sync: ownership banners"
    local deadline=$(( $(date +%s) + API_WAIT ))   # one budget shared by every instance
    for s in $insts; do
        [[ "$(env_get "$(trash_envkey "$s")")" == skip ]] && continue
        arr_api_ready "$s" "$deadline" || continue
        trash_sentinel "$s"
    done
    hr "trash-sync: recyclarr"
    local slog rc summary
    slog=$(mktemp)
    if (( WIRE_DRY )); then
        # -t: force a pseudo-TTY even though our stdout is a pipe — without it
        # recyclarr enters log mode and prints no preview at all
        DC run --rm -t --no-deps recyclarr sync --preview --config /config/recyclarr.preview.yml 2>&1 | tee "$slog"
        rc=${PIPESTATUS[0]}
        sudo rm -f "$preview"
        summary=$(trash_preview_summarize "$slog"); rm -f "$slog"
        WIRE_CHANGES=$((WIRE_CHANGES + ${summary%%|*})); summary=${summary#*|}
        if (( rc != 0 )); then
            wfail "recyclarr preview failed — output above is the evidence"
        elif [[ "$summary" == FAIL ]]; then
            wfail "recyclarr rendered no '(Preview)' blocks — drift UNCONFIRMED (a clean preview prints one block per pipeline per instance; check the output above and: docs/trash-sync.md)"
        else
            ok "preview complete — $summary"
        fi
        echo
        if (( WIRE_FAILS )); then fail "dry-run finished with $WIRE_FAILS failure(s)."; return 1; fi
        info "dry-run complete: $WIRE_CHANGES change(s) would be applied. Run without --dry-run to apply."
        return 0
    fi
    # keep the pinned :8 tag current (patch releases only — a major bump is
    # a schema migration and stays a deliberate, manual tag change)
    DC pull -q recyclarr 2>/dev/null \
        && info "recyclarr image: pinned tag up to date" \
        || warn "recyclarr image pull failed (registry unreachable?) — syncing with the local image"
    DC run --rm --no-deps recyclarr sync 2>&1 | tee "$slog"
    rc=${PIPESTATUS[0]}
    summary=$(trash_summarize "$slog")
    sudo install -m 644 "$slog" cache/trash-sync.log; rm -f "$slog"
    if (( rc == 0 )); then
        date +%s | sudo tee cache/trash-last-sync >/dev/null
        printf '%s' "$summary" | sudo tee cache/trash-last-summary >/dev/null
        ok "sync complete — $summary (full log: cache/trash-sync.log)"
    else
        wfail "recyclarr sync failed — output above is the evidence (also: cache/trash-sync.log)"
    fi
    if (( WIRE_FAILS )); then
        fail "trash-sync finished with $WIRE_FAILS failure(s)."; return 1
    fi
    ok "trash-sync complete."
}
