#!/usr/bin/env bash
# services/meilisearch/meilisearch.sh — Meilisearch's master key, generated by
# configure. Sourced by the entrypoint; relies on lib/common.sh at call time.
meilisearch_configure_secret() { # configure: its master key (a machine secret), generated once
    if [[ -z "$(env_get MEILI_MASTER_KEY)" ]]; then
        env_set MEILI_MASTER_KEY "$(openssl rand -base64 32 2>/dev/null || head -c32 /dev/urandom | base64)"
        ok "Generated Meilisearch master key (machine secret — you never need it)."
    fi
}
