#!/usr/bin/env bash
# test-audit.sh — deletion attribution's host contract and its log.
#   * the rules file: byte-stable for the same inputs, watch rules only
#     (auditd's own settings belong to the host), one rule per ABI the host
#     has, calls taken from ausyscall (ARM lacks unlink/rename/rmdir)
#   * the "who installed auditd" marker round-trips; auditctl is looked for
#     as root (it lives in /usr/sbin, off the operator's PATH)
#   * the parser, against scripts/fixtures/audit.raw and audit2.raw (real
#     captures, scrubbed of personal data: operator and container deletes, a
#     rename, a rename over an existing file, a relative path, hex-encoded
#     names, rm -r naming files only relative to an open folder, rule loads,
#     canaries) and audit-synthetic.raw (hand-built for what they lack:
#     log_format=RAW, a person through sudo, a shared UID whose services
#     disagree on the host path, an unknown UID, an event of an unknown shape,
#     a folder the batch never saw, a nested rm -r) -> audit.expected
#   * every awk the stack may meet (mawk is Debian's default, gawk elsewhere)
#     gives the same answers — found live: mawk labelled every service "|name"
#   * the hourly copy: new events once (never twice), a gap when auditd
#     rotated first, pruning to AUDIT_KEEP_DAYS
#   * teardown removes exactly the footprint — the package only when
#     mediastack installed it and nothing else has started using it
#
#   scripts/test-audit.sh     run (exit 1 on the first failed check)
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

lib=$(mktemp .test-audit.XXXXXX)
T=$(mktemp -d)
trap 'rm -rf "$lib" "$T"' EXIT
sed '$d' mediastack.sh > "$lib"
# shellcheck disable=SC1090
source "$lib"

checks=0
pass()  { checks=$((checks+1)); }
fail_() { echo "FAIL: $*" >&2; exit 1; }
ok() { :; }; info() { :; }; warn() { :; }
export TZ=Etc/GMT+3   # UTC-3: the fixtures' events fall on two local days

# ---- the rules file ----
a=$(audit_rules_render /srv/media yes unlink,rmdir unlinkat); b=$(audit_rules_render /srv/media yes unlink,rmdir unlinkat)
[[ "$a" == "$b" ]] || fail_ "the same inputs rendered two different rules files"; pass
want="# Generated by mediastack.sh — do not edit. Rewrite: ./mediastack.sh audit on   Remove: ./mediastack.sh audit off
# Watch rules only: auditd's own settings (buffers, failure mode, lock) are never set here.
# mediastack-installed-auditd: yes
-a always,exit -F arch=b64 -S unlink,rmdir -F dir=/srv/media -F success=1 -k mediastack-media
-a always,exit -F arch=b32 -S unlinkat -F dir=/srv/media -F success=1 -k mediastack-media"
[[ "$a" == "$want" ]] || fail_ "rules file changed:
$(diff <(echo "$want") <(echo "$a") || true)"; pass
[[ "$(audit_rules_render /srv/media yes unlinkat "" | grep -c '^-a')" == 1 ]] || fail_ "no 32-bit calls must mean no b32 rule"; pass
if grep -E '^(-[bfeDr]|--backlog)' <<<"$a"; then
    fail_ "the rules file sets an auditd setting (above) — those are the host's, never mediastack's"
fi; pass

# ---- architectures ----
[[ "$(audit_abi b64 x86_64)" == x86_64 && "$(audit_abi b32 x86_64)" == i386 ]] || fail_ "x86_64 ABIs"; pass
[[ "$(audit_abi b64 aarch64)" == aarch64 && "$(audit_abi b32 aarch64)" == arm ]] || fail_ "aarch64 ABIs"; pass
[[ -z "$(audit_abi b32 riscv64)" ]] || fail_ "riscv64 has no 32-bit ABI to watch"; pass
if audit_abi b64 armv7l >/dev/null; then fail_ "a 32-bit kernel must be refused"; fi; pass
sudo() { "$@"; }
ausyscall() { [[ "$3" == --exact ]] || return 2; case "$1:$2" in aarch64:unlink|aarch64:rename|aarch64:rmdir) return 1 ;; esac; echo 1; }
[[ "$(audit_syscalls_for aarch64)" == unlinkat,renameat,renameat2 ]] || fail_ "aarch64 calls: $(audit_syscalls_for aarch64)"; pass
[[ "$(audit_syscalls_for x86_64)" == unlink,unlinkat,rename,renameat,renameat2,rmdir ]] || fail_ "x86_64 calls: $(audit_syscalls_for x86_64)"; pass
unset -f ausyscall

# ---- the marker round-trips; no file, no marker ----
AUDIT_RULES=$T/rules.d/99-mediastack.rules
# shellcheck disable=SC2034  # read by the sourced audit_teardown / _doctor_audit
AUDIT_FOOTPRINT=("$AUDIT_RULES" "$T/unit.service" "$T/unit.timer")
mkdir -p "$T/rules.d"
[[ -z "$(audit_marker)" ]] || fail_ "no rules file must mean no marker"; pass
audit_rules_render /srv/media no unlink > "$AUDIT_RULES"
[[ "$(audit_marker)" == no ]] || fail_ "marker 'no' did not round-trip: '$(audit_marker)'"; pass
audit_rules_render /srv/media yes unlink > "$AUDIT_RULES"
[[ "$(audit_marker)" == yes ]] || fail_ "marker 'yes' did not round-trip: '$(audit_marker)'"; pass

# ---- auditctl -s ----
st=$'enabled 1\nfailure 1\npid 812\nrate_limit 0\nbacklog_limit 8192\nlost 7\nbacklog 0'
[[ "$(audit_stat_field lost <<<"$st")" == 7 ]] || fail_ "lost not parsed"; pass
[[ "$(audit_stat_field backlog_limit <<<"$st")" == 8192 ]] || fail_ "backlog_limit not parsed"; pass
[[ -z "$(audit_stat_field nope <<<"$st")" ]] || fail_ "an absent field must be empty"; pass

# ---- shared UIDs ----
ENV_FILE=$T/env
printf 'SONARR_UID=13001\nRADARR_UID=13002\nDELUGE_UID=13007\nTRANSMISSION_UID=13007\nOLIVETIN_UID=\nMEDIA_GROUP_GID=13001\n' > "$ENV_FILE"
[[ "$(audit_uid_dupes)" == "13007 " ]] || fail_ "shared UID not found (a GID must not count): '$(audit_uid_dupes)'"; pass
printf 'OTHER=1\n' > "$ENV_FILE"
[[ -z "$(audit_uid_dupes)" ]] || fail_ "no UIDs must mean no duplicates"; pass

# ---- auditctl lives in /usr/sbin: off the operator's PATH, on sudo's ----
# (found live: a check made as the operator saw no auditd, so 'audit on'
# reported none of its loaded rules — and would have claimed a host's own
# auditd as mediastack's install)
mkdir -p "$T/sbin"
printf '#!/bin/sh\n[ "$1" = -l ] && printf -- "-a always,exit -F dir=/srv/media -F key=mediastack-media\\n%%.0s" 1 2\n' > "$T/sbin/auditctl"
chmod +x "$T/sbin/auditctl"
sudo() { PATH="$T/sbin:$PATH" "$@"; }
if command -v auditctl >/dev/null 2>&1; then fail_ "auditctl on the test's own PATH — the check below would prove nothing"; fi
audit_have || fail_ "auditd present on root's PATH was not seen"; pass
[[ "$(audit_loaded_count)" == 2 ]] || fail_ "loaded rules not seen through sudo: $(audit_loaded_count)"; pass
sudo() { "$@"; }

# ---- the parser: real capture + synthetic cases -> the durable log ----
printf '13002\tradarr\n13001\tsonarr\n13007\tdeluge|transmission\n' > "$T/umap"
printf 'radarr\t/data\t/srv/mediastack/data\nradarr\t/config\t/srv/mediastack/config/radarr\nsonarr\t/data\t/srv/mediastack/data\ndeluge\t/data/torrent\t/srv/mediastack/data/torrent\ntransmission\t/data\t/mnt/elsewhere\n' > "$T/mounts"
printf '1000\toperator\n' > "$T/users"
FIXTURES=(scripts/fixtures/audit.raw scripts/fixtures/audit2.raw scripts/fixtures/audit-synthetic.raw)
parse_all() { local f; for f in "${FIXTURES[@]}"; do audit_parse 0 0 < "$f"; done \
                | grep '^E' | audit_attribute /srv/mediastack/data/media "$T/umap" "$T/mounts" "$T/users"; }
uidmap_of() { # the real audit_uidmap over a fixed service set (two services share 13007)
    render() { :; }; svc_managed() { printf '%s\n' radarr deluge transmission; }
    env_get() { case "$1" in RADARR_UID) echo 13002 ;; DELUGE_UID|TRANSMISSION_UID) echo 13007 ;; esac; }
    audit_uidmap
}
awks=(); for a in mawk gawk; do command -v "$a" >/dev/null && awks+=("$a"); done
(( ${#awks[@]} )) || fail_ "neither mawk nor gawk is installed"
for a in "${awks[@]}"; do
    got=$(awk() { "$a" "$@"; }; parse_all)
    [[ "$got" == "$(cat scripts/fixtures/audit.expected)" ]] || fail_ "$a: parsed log differs from scripts/fixtures/audit.expected:
$(diff scripts/fixtures/audit.expected <(echo "$got") || true)"; pass
    got=$(awk() { "$a" "$@"; }; uidmap_of)
    [[ "$got" == $'13002\tradarr\n13007\tdeluge|transmission' ]] || fail_ "$a: uid map: $(cat -A <<<"$got")"; pass
done
[[ "$(audit_parse 0 0 < scripts/fixtures/audit.raw | grep '^L')" == $'L\t1790390565.868\t999' ]] \
    || fail_ "the newest event (serials restart at boot: newest by time, not by serial) was not reported"; pass
[[ "$(audit_parse 1790390565.696 977 < scripts/fixtures/audit.raw | grep -c '^E')" == 2 ]] \
    || fail_ "events up to the last copied one must not be copied again"; pass

# ---- the hourly copy ----
env_file_audit() { printf 'AUDIT_ENABLED=true\nAUDIT_KEEP_DAYS=%s\nBACKUP_ROOT=%s\n' "$1" "$T/backups" > "$ENV_FILE"; }
env_file_audit 365
# shellcheck disable=SC2034  # read by the sourced audit_extract
AUDIT_LOCK=$T/lock
ausearch() { cat "${FIXTURES[@]}"; }
audit_uidmap() { cat "$T/umap"; }; audit_mounts() { cat "$T/mounts"; }
audit_root() { echo /srv/mediastack/data/media; }
getent() { [[ "$2" == 1000 ]] && echo "operator:x:1000:1000::/home/operator:/bin/bash"; }
OLDEST=""; audit_log_oldest() { echo "$OLDEST"; }
notify() { echo "$2" >> "$T/notified"; }
audit_extract
[[ "$(cat "$T/backups/audit/"*.tsv)" == "$(cat scripts/fixtures/audit.expected)" ]] || fail_ "first copy differs from audit.expected"; pass
[[ "$(ls "$T/backups/audit")" == $'2026-09-25.tsv\n2026-09-26.tsv' ]] || fail_ "events must land in their local day's file: $(ls "$T/backups/audit")"; pass
[[ "$(cat "$T/backups/audit/.last")" == "1790400000.802 2010" ]] || fail_ ".last: $(cat "$T/backups/audit/.last")"; pass
[[ "$(stat -c %a "$T/backups/audit/2026-09-25.tsv")" == 600 ]] || fail_ "day files must be private (600)"; pass
audit_extract
[[ "$(cat "$T/backups/audit/"*.tsv | wc -l)" == 16 ]] || fail_ "a second copy duplicated events"; pass
echo 100 > "$T/backups/audit/.ran"; OLDEST=200; audit_extract
grep -q $'\tgap\t' "$T/backups/audit/"*.tsv || fail_ "auditd rotating past the last copy was not logged as a gap"; pass
grep -q 'gap' "$T/notified" || fail_ "a gap was not notified"; pass
OLDEST=""
env_file_audit 1
: > "$T/backups/audit/2026-01-01.tsv"
audit_prune "$T/backups/audit"
[[ ! -e "$T/backups/audit/2026-01-01.tsv" ]] || fail_ "a day file past AUDIT_KEEP_DAYS was not pruned"; pass
env_file_audit 0
if (audit_keep_days) 2>/dev/null; then fail_ "AUDIT_KEEP_DAYS=0 must be refused"; fi; pass
env_file_audit 365
sed -i 's/AUDIT_ENABLED=true/AUDIT_ENABLED=false/' "$ENV_FILE"
if (audit_extract) 2>/dev/null; then fail_ "a copy with attribution off must fail loud (a leftover timer)"; fi; pass

# ---- who removed a folder (the manifest's alert asks this) ----
BACKUP_ROOT_W=$T/who; mkdir -p "$BACKUP_ROOT_W/audit"
audit_dir() { echo "$BACKUP_ROOT_W/audit"; }
audit_root() { echo /srv/mediastack/data/media; }
cp scripts/fixtures/audit.expected "$BACKUP_ROOT_W/audit/$(printf '%(%F)T' 1790391835).tsv"
got=$(printf '%s\n' '.x y' 'movies/Film' 'music' 'tv/none' | audit_whodunit 1790391000 1790400000)
[[ "$got" == $'.x y\tradarr ×2\nmovies/Film\toperator ×3\nmusic\toperator (as root) ×1\ntv/none\t-' ]] \
    || fail_ "who removed each folder: $(cat -A <<<"$got")"; pass
[[ "$(echo 'movies/Film' | audit_whodunit 1790391900 1790395000)" == $'movies/Film\t-' ]] \
    || fail_ "an event outside the window (same day file) must not count"; pass
printf '1790395000\t-\tgap\tx .. y\t\n' >> "$BACKUP_ROOT_W/audit/$(printf '%(%F)T' 1790391835).tsv"
[[ "$(echo 'tv/none' | audit_whodunit 1790391000 1790400000)" == $'tv/none\t-gap' ]] \
    || fail_ "no record plus a gap in the window must say so"; pass
[[ "$(audit_whodunit_text -gap)" == *"gap"* && "$(audit_whodunit_text 'radarr ×2')" == "removed by: radarr ×2" ]] || fail_ "whodunit sentences"; pass
rm -rf "$BACKUP_ROOT_W"; unset -f audit_dir

# ---- report ----
audit_report_args --since 2026-09-01 --path Film
[[ "$REPORT_SINCE" == 2026-09-01 && "$REPORT_PATH" == Film ]] || fail_ "report args"; pass
if (audit_report_args --since 2026-02-30) 2>/dev/null; then fail_ "an impossible date must be refused"; fi; pass
if (audit_report_args --bogus) 2>/dev/null; then fail_ "an unknown report argument must be refused"; fi; pass
out=$(audit_report_format "A B.MKV" < scripts/fixtures/audit.expected)
[[ "$out" == *".x y/a b.mkv"* && "$out" != *"/.t"* ]] || fail_ "report --path must match case-insensitively and only the match:
$out"; pass
if (cmd_audit on extra) 2>/dev/null; then fail_ "'audit on extra' must be refused"; fi; pass
if (cmd_audit bogus) 2>/dev/null; then fail_ "an unknown audit action must be refused"; fi; pass

# ---- teardown ----
# a fake kernel, on root's PATH only: auditctl -l lists $T/loaded, -D -k
# empties it; apt-get and systemctl log
loaded=$T/loaded
printf '#!/bin/sh\ncase "$1" in -l) cat "%s" ;; -D) : > "%s" ;; esac\n' "$loaded" "$loaded" > "$T/sbin/auditctl"
sudo() { PATH="$T/sbin:$PATH" "$@"; }
apt-get() { echo "$*" >> "$T/apt"; }
systemctl() { :; }
confirm() { return 0; }
# shellcheck disable=SC2034  # read by the sourced audit_teardown
AUDIT_LOGDIR=$T/log
setup() { # setup MARK — a live watch installed with that marker
    audit_rules_render /srv/media "$1" unlink > "$AUDIT_RULES"
    touch "$T/unit.service" "$T/unit.timer"
    printf -- '-a always,exit -F dir=/srv/media -F key=mediastack-media\n%.0s' 1 2 > "$loaded"
    mkdir -p "$AUDIT_LOGDIR"; rm -f "$T/apt"
}

setup no; audit_teardown yes
[[ ! -e "$AUDIT_RULES" && ! -e "$T/unit.timer" && ! -e "$T/unit.service" && ! -s "$loaded" ]] \
    || fail_ "teardown left part of the footprint or loaded rules"; pass
[[ ! -e "$T/apt" && -d "$AUDIT_LOGDIR" ]] || fail_ "teardown touched an auditd mediastack did not install"; pass

setup yes; touch "$T/rules.d/10-theirs.rules"; audit_teardown yes
[[ ! -e "$T/apt" && -d "$AUDIT_LOGDIR" ]] || fail_ "teardown removed auditd while other rules use it"; pass
rm "$T/rules.d/10-theirs.rules"

setup yes; : > "$T/rules.d/audit.rules"; audit_teardown yes   # the package's own file is not 'someone else'
grep -q '^purge -y -qq auditd$' "$T/apt" 2>/dev/null || fail_ "teardown kept the auditd it installed"; pass
[[ ! -e "$AUDIT_LOGDIR" ]] || fail_ "teardown kept the logs of the auditd it installed"; pass

setup yes; confirm() { return 1; }; audit_teardown ask
[[ ! -e "$T/apt" && -d "$AUDIT_LOGDIR" ]] || fail_ "a declined 'remove auditd too?' still removed it"; pass

echo "OK audit: $checks checks"
