#!/usr/bin/env bash
# test-audit.sh — deletion attribution's host contract. The rules file is
# byte-stable for the same inputs and holds watch rules only (auditd's own
# settings belong to the host); the "who installed auditd" marker round-trips
# through the file; the kernel's status lines parse; shared UIDs are found;
# and teardown removes exactly the footprint — the package only when
# mediastack installed it and nothing else has started using it.
#
#   scripts/test-audit.sh     run (exit 1 on the first failed check)
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

lib=$(mktemp .test-audit.XXXXXX)
T=$(mktemp -d)
trap 'rm -rf "$lib" "$T"' EXIT
sed '$d' mediastack.sh > "$lib"
# shellcheck disable=SC1090
source "$lib"

checks=0
pass()  { checks=$((checks+1)); }
fail_() { echo "FAIL: $*" >&2; exit 1; }

# ---- the rules file ----
a=$(audit_rules_render /srv/media yes); b=$(audit_rules_render /srv/media yes)
[[ "$a" == "$b" ]] || fail_ "the same inputs rendered two different rules files"; pass
want="# Generated by mediastack.sh — do not edit. Rewrite: ./mediastack.sh audit on   Remove: ./mediastack.sh audit off
# Watch rules only: auditd's own settings (buffers, failure mode, lock) are never set here.
# mediastack-installed-auditd: yes
-a always,exit -F arch=b64 -S unlink,unlinkat,rename,renameat,renameat2,rmdir -F dir=/srv/media -F success=1 -k mediastack-media
-a always,exit -F arch=b32 -S unlink,unlinkat,rename,renameat,renameat2,rmdir -F dir=/srv/media -F success=1 -k mediastack-media"
[[ "$a" == "$want" ]] || fail_ "rules file changed:
$(diff <(echo "$want") <(echo "$a") || true)"; pass
if grep -E '^(-[bfeDr]|--backlog)' <<<"$a"; then
    fail_ "the rules file sets an auditd setting (above) — those are the host's, never mediastack's"
fi; pass

# ---- the marker round-trips; no file, no marker ----
sudo() { "$@"; }
AUDIT_RULES=$T/rules.d/99-mediastack.rules
# shellcheck disable=SC2034  # read by the sourced audit_teardown
AUDIT_FOOTPRINT=("$AUDIT_RULES")
mkdir -p "$T/rules.d"
[[ -z "$(audit_marker)" ]] || fail_ "no rules file must mean no marker"; pass
audit_rules_render /srv/media no > "$AUDIT_RULES"
[[ "$(audit_marker)" == no ]] || fail_ "marker 'no' did not round-trip: '$(audit_marker)'"; pass
audit_rules_render /srv/media yes > "$AUDIT_RULES"
[[ "$(audit_marker)" == yes ]] || fail_ "marker 'yes' did not round-trip: '$(audit_marker)'"; pass

# ---- auditctl -s ----
st=$'enabled 1\nfailure 1\npid 812\nrate_limit 0\nbacklog_limit 8192\nlost 7\nbacklog 0'
[[ "$(audit_stat_field lost <<<"$st")" == 7 ]] || fail_ "lost not parsed"; pass
[[ "$(audit_stat_field backlog_limit <<<"$st")" == 8192 ]] || fail_ "backlog_limit not parsed"; pass
[[ -z "$(audit_stat_field nope <<<"$st")" ]] || fail_ "an absent field must be empty"; pass

# ---- shared UIDs ----
ENV_FILE=$T/env
printf 'SONARR_UID=13001\nRADARR_UID=13002\nDELUGE_UID=13007\nTRANSMISSION_UID=13007\nOLIVETIN_UID=\nMEDIA_GROUP_GID=13001\n' > "$ENV_FILE"
[[ "$(audit_uid_dupes)" == "13007 " ]] || fail_ "shared UID not found (a GID must not count): '$(audit_uid_dupes)'"; pass
printf 'OTHER=1\n' > "$ENV_FILE"
[[ -z "$(audit_uid_dupes)" ]] || fail_ "no UIDs must mean no duplicates"; pass

# ---- teardown ----
# a fake kernel: auditctl -l lists $T/loaded, -D -k empties it; apt-get logs
loaded=$T/loaded
auditctl() { case "$1" in -l) cat "$loaded" ;; -D) : > "$loaded" ;; esac; }
apt-get() { echo "$*" >> "$T/apt"; }
confirm() { return 0; }
ok() { :; }; info() { :; }; warn() { :; }
AUDIT_LOGDIR=$T/log; setup() { # setup MARK — a live watch installed with that marker
    audit_rules_render /srv/media "$1" > "$AUDIT_RULES"
    printf -- '-a always,exit -F dir=/srv/media -F key=mediastack-media\n%.0s' 1 2 > "$loaded"
    mkdir -p "$AUDIT_LOGDIR"; rm -f "$T/apt"
}

setup no; audit_teardown yes
[[ ! -e "$AUDIT_RULES" && ! -s "$loaded" ]] || fail_ "teardown left the rules file or loaded rules"; pass
[[ ! -e "$T/apt" && -d "$AUDIT_LOGDIR" ]] || fail_ "teardown touched an auditd mediastack did not install"; pass

setup yes; touch "$T/rules.d/10-theirs.rules"; audit_teardown yes
[[ ! -e "$T/apt" && -d "$AUDIT_LOGDIR" ]] || fail_ "teardown removed auditd while other rules use it"; pass
rm "$T/rules.d/10-theirs.rules"

setup yes; : > "$T/rules.d/audit.rules"; audit_teardown yes   # the package's own file is not 'someone else'
grep -q '^purge -y -qq auditd$' "$T/apt" 2>/dev/null || fail_ "teardown kept the auditd it installed"; pass
[[ ! -e "$AUDIT_LOGDIR" ]] || fail_ "teardown kept the logs of the auditd it installed"; pass

setup yes; confirm() { return 1; }; audit_teardown ask
[[ ! -e "$T/apt" && -d "$AUDIT_LOGDIR" ]] || fail_ "a declined 'remove auditd too?' still removed it"; pass

echo "OK audit: $checks checks"
